from django.urls import path

from .calendar_views import (
    GoogleCalendarDestinationsView,
    GoogleCalendarEventsView,
    GoogleCalendarImportPreviewView,
    GoogleCalendarImportView,
    GoogleCalendarListView,
)
from .views import (
    GmailDestinationsView,
    GmailImportPreviewView,
    GmailImportView,
    GmailMessageAttachmentsView,
    GmailMessagesView,
    GoogleDriveDestinationsView,
    GoogleDriveFilesView,
    GoogleDriveImportPreviewView,
    GoogleDriveImportView,
    GoogleOAuthCallbackView,
    GoogleOAuthStartView,
    IntegrationAccountDisconnectView,
    IntegrationAccountHealthView,
    IntegrationAccountRefreshView,
    IntegrationAccountsView,
    IntegrationProvidersView,
)

urlpatterns = [
    path(
        "integrations/providers/",
        IntegrationProvidersView.as_view(),
        name="integration-providers",
    ),
    path(
        "integrations/accounts/",
        IntegrationAccountsView.as_view(),
        name="integration-accounts",
    ),
    path(
        "integrations/google/start/",
        GoogleOAuthStartView.as_view(),
        name="integration-google-start",
    ),
    path(
        "integrations/google/callback/",
        GoogleOAuthCallbackView.as_view(),
        name="integration-google-callback",
    ),
    path(
        "integrations/accounts/<int:pk>/disconnect/",
        IntegrationAccountDisconnectView.as_view(),
        name="integration-account-disconnect",
    ),
    path(
        "integrations/accounts/<int:pk>/refresh/",
        IntegrationAccountRefreshView.as_view(),
        name="integration-account-refresh",
    ),
    path(
        "integrations/accounts/<int:pk>/health/",
        IntegrationAccountHealthView.as_view(),
        name="integration-account-health",
    ),
    # ---- Google Drive Import V1 ----
    path(
        "integrations/google-drive/files/",
        GoogleDriveFilesView.as_view(),
        name="integration-google-drive-files",
    ),
    path(
        "integrations/google-drive/destinations/",
        GoogleDriveDestinationsView.as_view(),
        name="integration-google-drive-destinations",
    ),
    path(
        "integrations/google-drive/import/preview/",
        GoogleDriveImportPreviewView.as_view(),
        name="integration-google-drive-import-preview",
    ),
    path(
        "integrations/google-drive/import/",
        GoogleDriveImportView.as_view(),
        name="integration-google-drive-import",
    ),
    # ---- Gmail Import V1 ----
    path(
        "integrations/gmail/messages/",
        GmailMessagesView.as_view(),
        name="integration-gmail-messages",
    ),
    path(
        "integrations/gmail/messages/<str:message_id>/attachments/",
        GmailMessageAttachmentsView.as_view(),
        name="integration-gmail-message-attachments",
    ),
    path(
        "integrations/gmail/destinations/",
        GmailDestinationsView.as_view(),
        name="integration-gmail-destinations",
    ),
    path(
        "integrations/gmail/import/preview/",
        GmailImportPreviewView.as_view(),
        name="integration-gmail-import-preview",
    ),
    path(
        "integrations/gmail/import/",
        GmailImportView.as_view(),
        name="integration-gmail-import",
    ),
    # ---- Google Calendar import (manual, read-only, review-before-save) ----
    path(
        "integrations/google-calendar/destinations/",
        GoogleCalendarDestinationsView.as_view(),
        name="integration-google-calendar-destinations",
    ),
    path(
        "integrations/google-calendar/calendars/",
        GoogleCalendarListView.as_view(),
        name="integration-google-calendar-calendars",
    ),
    path(
        "integrations/google-calendar/events/",
        GoogleCalendarEventsView.as_view(),
        name="integration-google-calendar-events",
    ),
    path(
        "integrations/google-calendar/import/preview/",
        GoogleCalendarImportPreviewView.as_view(),
        name="integration-google-calendar-import-preview",
    ),
    path(
        "integrations/google-calendar/import/",
        GoogleCalendarImportView.as_view(),
        name="integration-google-calendar-import",
    ),
]
