from django.urls import path

from .views import (
    GoogleDriveDestinationsView,
    GoogleDriveFilesView,
    GoogleDriveImportPreviewView,
    GoogleDriveImportView,
    GoogleOAuthCallbackView,
    GoogleOAuthStartView,
    IntegrationAccountDisconnectView,
    IntegrationAccountHealthView,
    IntegrationAccountRefreshView,
    IntegrationAccountsView,
    IntegrationProvidersView,
)

urlpatterns = [
    path(
        "integrations/providers/",
        IntegrationProvidersView.as_view(),
        name="integration-providers",
    ),
    path(
        "integrations/accounts/",
        IntegrationAccountsView.as_view(),
        name="integration-accounts",
    ),
    path(
        "integrations/google/start/",
        GoogleOAuthStartView.as_view(),
        name="integration-google-start",
    ),
    path(
        "integrations/google/callback/",
        GoogleOAuthCallbackView.as_view(),
        name="integration-google-callback",
    ),
    path(
        "integrations/accounts/<int:pk>/disconnect/",
        IntegrationAccountDisconnectView.as_view(),
        name="integration-account-disconnect",
    ),
    path(
        "integrations/accounts/<int:pk>/refresh/",
        IntegrationAccountRefreshView.as_view(),
        name="integration-account-refresh",
    ),
    path(
        "integrations/accounts/<int:pk>/health/",
        IntegrationAccountHealthView.as_view(),
        name="integration-account-health",
    ),
    # ---- Google Drive Import V1 ----
    path(
        "integrations/google-drive/files/",
        GoogleDriveFilesView.as_view(),
        name="integration-google-drive-files",
    ),
    path(
        "integrations/google-drive/destinations/",
        GoogleDriveDestinationsView.as_view(),
        name="integration-google-drive-destinations",
    ),
    path(
        "integrations/google-drive/import/preview/",
        GoogleDriveImportPreviewView.as_view(),
        name="integration-google-drive-import-preview",
    ),
    path(
        "integrations/google-drive/import/",
        GoogleDriveImportView.as_view(),
        name="integration-google-drive-import",
    ),
]
