# Generated by Django 5.2.15 on 2026-06-14 11:38

import apps.notifications.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('document_reminders_enabled', models.BooleanField(default=True)),
                ('subscription_reminders_enabled', models.BooleanField(default=True)),
                ('checklist_bundle_reminders_enabled', models.BooleanField(default=True)),
                ('organization_reminders_enabled', models.BooleanField(default=True)),
                ('emergency_reminders_enabled', models.BooleanField(default=True)),
                ('security_alerts_enabled', models.BooleanField(default=True)),
                ('activity_notifications_enabled', models.BooleanField(default=False)),
                ('reminder_digest_enabled', models.BooleanField(default=False)),
                ('default_reminder_lead_days', models.JSONField(blank=True, default=apps.notifications.models.default_lead_days)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document_expiry', 'Document expiry'), ('document_renewal', 'Document renewal'), ('document_missing_file', 'Document missing file'), ('document_review_needed', 'Document review needed'), ('subscription_renewal', 'Subscription renewal'), ('subscription_cancellation_deadline', 'Subscription cancellation deadline'), ('subscription_trial_ending', 'Subscription trial ending'), ('subscription_payment_due', 'Subscription payment due'), ('subscription_payment_overdue', 'Subscription payment overdue'), ('bundle_deadline', 'Bundle deadline'), ('bundle_incomplete', 'Bundle incomplete'), ('checklist_item_due', 'Checklist item due'), ('checklist_missing_file', 'Checklist missing file'), ('organization_request_due', 'Organization request due'), ('organization_submission_review', 'Organization submission review'), ('organization_campaign_deadline', 'Organization campaign deadline'), ('organization_member_missing_document', 'Organization member missing document'), ('share_expiring', 'Share expiring'), ('room_expiring', 'Secure room expiring'), ('share_viewed', 'Share viewed'), ('emergency_review', 'Emergency review'), ('emergency_expiring', 'Emergency access expiring'), ('emergency_viewed', 'Emergency access viewed'), ('security_alert', 'Security alert'), ('failed_login_warning', 'Failed login warning'), ('storage_plan_warning', 'Storage/plan warning'), ('generic_reminder', 'Generic reminder')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('security', 'Security'), ('success', 'Success')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivered_in_app_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_email_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempts', models.PositiveSmallIntegerField(default=0)),
                ('email_last_error', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_cd4f27_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'), models.Index(fields=['type', 'scheduled_for'], name='notificatio_type_a7e7e6_idx'), models.Index(fields=['source_type', 'source_id'], name='notificatio_source__c43d4f_idx')],
            },
        ),
    ]
