# Generated by Django 5.2.15 on 2026-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some failures)'), ('failed', 'Failed')], default='success', max_length=12)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=12)),
                ('evaluated', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('existing', models.PositiveIntegerField(default=0)),
                ('in_app_delivered', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_skipped', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('skipped_preferences', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='notificatio_started_57a6fa_idx'), models.Index(fields=['status', '-started_at'], name='notificatio_status_f75752_idx')],
            },
        ),
    ]
