# Generated by Django 5.2.15 on 2026-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdeliveryrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('document_expiry', 'Document expiry'), ('document_renewal', 'Document renewal'), ('document_missing_file', 'Document missing file'), ('document_review_needed', 'Document review needed'), ('subscription_renewal', 'Subscription renewal'), ('subscription_cancellation_deadline', 'Subscription cancellation deadline'), ('subscription_trial_ending', 'Subscription trial ending'), ('subscription_payment_due', 'Subscription payment due'), ('subscription_payment_overdue', 'Subscription payment overdue'), ('bundle_deadline', 'Bundle deadline'), ('bundle_incomplete', 'Bundle incomplete'), ('checklist_item_due', 'Checklist item due'), ('checklist_missing_file', 'Checklist missing file'), ('organization_request_due', 'Organization request due'), ('organization_submission_review', 'Organization submission review'), ('organization_campaign_deadline', 'Organization campaign deadline'), ('organization_member_missing_document', 'Organization member missing document'), ('share_expiring', 'Share expiring'), ('room_expiring', 'Secure room expiring'), ('share_viewed', 'Share viewed'), ('emergency_review', 'Emergency review'), ('emergency_expiring', 'Emergency access expiring'), ('emergency_viewed', 'Emergency access viewed'), ('emergency_request', 'Emergency access requested'), ('emergency_unlock', 'Emergency access unlocked'), ('security_alert', 'Security alert'), ('failed_login_warning', 'Failed login warning'), ('storage_plan_warning', 'Storage/plan warning'), ('generic_reminder', 'Generic reminder')], max_length=64),
        ),
    ]
