# Generated by Django 5.2.15 on 2026-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference_push_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_end_hour',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_start_hour',
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
