# Generated by Django 5.2.15 on 2026-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreference_push_quiet_end_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('transactional', 'Transactional'), ('lifecycle', 'Lifecycle'), ('marketing', 'Marketing')], default='transactional', max_length=16)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent to provider'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Spam complaint')], default='sent', max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', '-created_at'], name='notificatio_email_t_e9837a_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuppressedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('scope', models.CharField(choices=[('all', 'All mail'), ('marketing', 'Marketing / lifecycle only')], default='all', max_length=12)),
                ('reason', models.CharField(choices=[('bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('unsubscribe', 'Unsubscribed'), ('manual', 'Manually suppressed')], default='bounce', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='notificatio_email_b2a42a_idx')],
            },
        ),
    ]
