# Generated by Django 5.2.15 on 2026-06-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_emaillog_suppressedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='ai_briefing_digest_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
