# Generated by Django 5.2.15 on 2026-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationpreference_ai_briefing_digest_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='weekly_radar_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
