# Generated by Django 5.2.15 on 2026-06-20 07:04

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quick_share', '0010_quicksharesession_verification_manifest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('expected_document_type', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='share_requests.sharerequest')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='share_requests.sharerequest')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_request_responses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_request_responses', to='quick_share.quicksharesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharerequest',
            index=models.Index(fields=['owner', 'created_at'], name='share_reque_owner_i_7b62e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerequest',
            index=models.Index(fields=['token'], name='share_reque_token_7eeff8_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerequestitem',
            index=models.Index(fields=['request', 'sort_order'], name='share_reque_request_3d1709_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharerequestresponse',
            constraint=models.UniqueConstraint(fields=('request', 'responder'), name='uniq_share_request_responder'),
        ),
    ]
