# Generated by Django 5.2.15 on 2026-06-22 05:42

import apps.share_requests.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerequest',
            name='allow_external_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShareRequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.share_requests.models.share_submission_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='share_requests.sharerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='share_reque_request_1cf52d_idx')],
            },
        ),
    ]
