# Generated by Django 5.2.15 on 2026-06-13 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_google_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_completed_document_onboarding', models.BooleanField(default=False)),
                ('first_document_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_file_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('first_expiry_date_added_at', models.DateTimeField(blank=True, null=True)),
                ('first_reminder_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_share_link_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_checklist_created_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_onboarding_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='users_accou_owner_i_203b5f_idx'), models.Index(fields=['scheduled_for'], name='users_accou_schedul_9412b8_idx')],
            },
        ),
    ]
