# Generated by Django 5.2.15 on 2026-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useronboardingstate_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro_placeholder', 'Pro (placeholder)')], default='free', max_length=32),
        ),
    ]
