# Generated by Django 5.2.15 on 2026-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
