# Generated by Django 5.2.15 on 2026-06-22 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_details', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_ciphertext', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
