# Generated by Django 5.2.15 on 2026-06-24 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_trackedapplication'),
        ('users', '0007_userprofiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smart_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_for_applications', models.EmailField(blank=True, max_length=254)),
                ('country_of_residence', models.CharField(blank=True, max_length=120)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('profile_completeness', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('work', 'Work'), ('leadership', 'Leadership'), ('volunteer', 'Volunteer'), ('award', 'Award'), ('certification', 'Certification'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_profile_achievements', to=settings.AUTH_USER_MODEL)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_profile_achievements', to='documents.document')),
            ],
            options={
                'ordering': ['sort_order', '-date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='users_smart_owner_i_911851_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartProfileCommonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('visa', 'Visa'), ('job', 'Job'), ('university', 'University'), ('general', 'General')], default='general', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_profile_common_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='users_smart_owner_i_79eb16_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('degree_or_program', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('grade_or_cgpa', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_profile_education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-end_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='users_smart_owner_i_50c9f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('language', 'Language'), ('soft', 'Soft'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_profile_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='users_smart_owner_i_90abce_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartProfileWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_profile_work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-end_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='users_smart_owner_i_45609f_idx')],
            },
        ),
    ]
