# Generated by Django 5.2.15 on 2026-06-23 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='unknown', max_length=64)),
                ('provider', models.CharField(default='anthropic', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('blocked', 'Blocked')], default='success', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aiusage_user_id_603473_idx'), models.Index(fields=['status', 'created_at'], name='ai_aiusage_status_ebfde0_idx'), models.Index(fields=['feature', 'created_at'], name='ai_aiusage_feature_14d21f_idx'), models.Index(fields=['provider', 'model'], name='ai_aiusage_provide_f63141_idx')],
            },
        ),
    ]
