# Generated by Django 5.2.15 on 2026-06-15 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_seed_request_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('family', 'Family'), ('organization', 'Organization')], default='pro', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('monthly_price', models.PositiveIntegerField(blank=True, null=True)),
                ('yearly_price', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_provider_price_id', models.CharField(blank=True, max_length=120)),
                ('yearly_provider_price_id', models.CharField(blank=True, max_length=120)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=20)),
                ('provider_customer_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('default_currency', models.CharField(default='usd', max_length=3)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('tax_region', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('promo_type', models.CharField(choices=[('percentage_discount', 'Percentage discount'), ('fixed_discount', 'Fixed discount'), ('trial_extension', 'Trial extension'), ('free_months', 'Free months'), ('founder_discount', 'Founder discount'), ('beta_access', 'Beta access'), ('student_discount', 'Student discount'), ('referral_credit', 'Referral credit'), ('manual_code', 'Manual code')], default='percentage_discount', max_length=24)),
                ('percent_off', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_off', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('duration', models.CharField(choices=[('once', 'First payment only'), ('repeating', 'Repeating'), ('forever', 'Forever')], default='once', max_length=12)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trial_extension_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redemptions_per_user', models.PositiveSmallIntegerField(default=1)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('applies_to_plans', models.JSONField(blank=True, default=list)),
                ('applies_to_billing_intervals', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_coupon_id', models.CharField(blank=True, max_length=120)),
                ('provider_promotion_code_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_customer_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('free', 'Free'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('grace_period', 'Grace period'), ('beta', 'Beta'), ('founder', 'Founder'), ('lifetime', 'Lifetime'), ('manual_pro', 'Manual Pro'), ('org_active', 'Organization active'), ('org_past_due', 'Organization past due')], default='free', max_length=24)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('lifetime', 'Lifetime'), ('none', 'None')], default='none', max_length=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.promocode')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duenest_subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duenest_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('provider_redemption_id', models.CharField(blank=True, max_length=120)),
                ('amount_discounted', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='billing.usersubscription')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_invoice_id', models.CharField(max_length=140, unique=True)),
                ('amount_due', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('hosted_invoice_url', models.URLField(blank=True)),
                ('invoice_pdf_url', models.URLField(blank=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_records', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to='billing.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=20)),
                ('provider_event_id', models.CharField(max_length=140, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='processed', max_length=12)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='billing.usersubscription')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_status', models.CharField(choices=[('free', 'Free'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('grace_period', 'Grace period'), ('beta', 'Beta'), ('founder', 'Founder'), ('lifetime', 'Lifetime'), ('manual_pro', 'Manual Pro'), ('org_active', 'Organization active'), ('org_past_due', 'Organization past due')], default='manual_pro', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_access_grants', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_grants', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='billing_man_user_id_11776d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=64)),
                ('limit_value', models.IntegerField(blank=True, null=True)),
                ('limit_period', models.CharField(choices=[('total', 'Total'), ('month', 'Per month'), ('day', 'Per day')], default='total', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'ordering': ['plan_id', 'feature_key'],
                'unique_together': {('plan', 'feature_key')},
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='billing_use_user_id_de2ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo_code', 'user'], name='billing_pro_promo_c_69d6f0_idx'),
        ),
    ]
