# Generated by Django 5.2.15 on 2026-06-19 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_featureusagecounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('email_link', 'Branded email + provider invoice link'), ('email_pdf', 'Branded email + DueNest PDF attachment'), ('email_only', 'Branded email only')], default='email_link', max_length=20)),
                ('send_for_manual', models.BooleanField(default=True)),
                ('business_legal_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt settings',
                'verbose_name_plural': 'Receipt settings',
            },
        ),
    ]
