# Generated by Django 5.2.15 on 2026-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoicerecord_receipt_sent_at_receiptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='last_receipt_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
