# Generated by Django 5.2.15 on 2026-06-20 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_enable_pro_trial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_ending_days_before', models.PositiveSmallIntegerField(default=3)),
                ('renewal_upcoming_days_before', models.PositiveSmallIntegerField(default=3)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=7)),
                ('dunning_followup_days', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing email settings',
                'verbose_name_plural': 'Billing email settings',
            },
        ),
    ]
