# Generated by Django 5.2.15 on 2026-06-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingemailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsettings',
            name='mode',
            field=models.CharField(choices=[('email_link', 'Branded email + provider invoice link'), ('email_pdf', 'Branded email + CertaNest PDF attachment'), ('email_only', 'Branded email only')], default='email_link', max_length=20),
        ),
    ]
