# Generated by Django 5.2.15 on 2026-06-13 22:06

import apps.subscriptions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscription categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_interval_count', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_interval_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('cancellation_deadline', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=7)),
                ('payment_method_label', models.CharField(blank=True, max_length=120, validators=[apps.subscriptions.models.validate_no_card_number])),
                ('importance', models.CharField(choices=[('essential', 'Essential'), ('useful', 'Useful'), ('optional', 'Optional'), ('rarely_used', 'Rarely used')], default='useful', max_length=20)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptioncategory')),
            ],
            options={
                'ordering': ['next_billing_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paid_on', models.DateField()),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptioncategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='uniq_system_subscription_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncategory',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_owner_subscription_category_slug'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'status'], name='subscriptio_owner_i_5b8766_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'next_billing_date'], name='subscriptio_owner_i_efd98b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'is_archived'], name='subscriptio_owner_i_d49244_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpaymentrecord',
            index=models.Index(fields=['owner', 'paid_on'], name='subscriptio_owner_i_51d528_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpaymentrecord',
            index=models.Index(fields=['subscription', 'paid_on'], name='subscriptio_subscri_d3aa4f_idx'),
        ),
    ]
