# Generated by Django 5.2.15 on 2026-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_change_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
