# Generated by Django 5.2.15 on 2026-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_cancel_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='provider_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
