# Generated by Django 5.2.15 on 2026-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_provider_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='attention_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
