from django.urls import path
from rest_framework.routers import DefaultRouter

from .scanner import UploadScannedDocumentView
from .views import (
    BundleExportDetailView,
    BundleExportDownloadView,
    BundleExportListCreateView,
    BundleProofRecordListView,
    BundleReadinessView,
    BundleReadinessSummaryView,
    RequirementLinkImportView,
    RequirementLinkImportApplyView,
    ApplicationListCreateView,
    ApplicationDetailView,
    ApplicationSummaryView,
    ApplicationDocumentTemplatesView,
    ApplicationDocumentGenerateView,
    ApplicationDocumentDetailView,
    ApplicationDocumentExportView,
    ApplicationDocumentSaveToPackView,
    MagicInboxListCreateView,
    MagicInboxDetailView,
    MagicInboxAnalyzeView,
    MagicInboxApplyView,
    MagicInboxArchiveView,
    DocumentRequestListCreateView,
    DocumentRequestDetailView,
    DocumentRequestSendView,
    DocumentRequestCancelView,
    DocumentRequestReviewView,
    DocumentRequestAcceptView,
    DocumentRequestRejectView,
    DocumentRequestNeedsReplacementView,
    DocumentRequestSaveToVaultView,
    DocumentRequestAttachToPackView,
    PublicDocumentRequestMetadataView,
    PublicDocumentRequestUploadView,
    SharingRoomListCreateView,
    SharingRoomDetailView,
    SharingRoomAddItemView,
    SharingRoomRemoveItemView,
    SharingRoomRevokeView,
    SharingRoomArchiveView,
    SharingRoomFromPackView,
    SharingRoomFromApplicationView,
    PublicSharingRoomMetadataView,
    PublicSharingRoomFilePreviewView,
    PublicSharingRoomFileDownloadView,
    ProtectedCopyListCreateView,
    ProtectedCopyDetailView,
    ProtectedCopyGenerateView,
    ProtectedCopyArchiveView,
    ProtectedCopyAddToRoomView,
    AuditLogListView,
    AuditLogDetailView,
    AuditLogSummaryView,
    BundleRequirementLinkDocumentView,
    BundleRequirementLinkFileView,
    ChecklistTemplateDetailView,
    ChecklistTemplateListView,
    DocumentActivityTimelineView,
    DocumentAppointmentViewSet,
    DocumentBundleDetailView,
    DocumentBundleExportFilesView,
    DocumentBundleExportMergedPdfView,
    DocumentBundleExportSelectedFilesView,
    DocumentBundleFilesView,
    DocumentBundleListCreateView,
    BundleActivityTimelineView,
    BundleShareReadinessView,
    BundleAddDocumentsView,
    DocumentsBulkExportView,
    PackTemplatesView,
    CalendarEventsView,
    CalendarIcsExportView,
    CalendarSummaryView,
    DocumentFilesExportSelectedView,
    PublicShareRoomFileDownloadView,
    PublicShareRoomFilePreviewView,
    PublicShareRoomMetadataView,
    PublicShareRoomVerifyCodeView,
    PublicShareRoomZipView,
    ShareRoomActivityView,
    ShareRoomDetailView,
    ShareRoomItemDeleteView,
    ShareRoomItemsView,
    ShareRoomListCreateView,
    ShareRoomRevokeView,
    DocumentBundleRequirementCreateView,
    DocumentBundleRequirementDetailView,
    DocumentHealthOverviewView,
    DocumentMissingScanView,
    DocumentPaymentViewSet,
    DocumentRenewalEventDetailView,
    DocumentRenewalEventListCreateView,
    DocumentTagViewSet,
    DocumentChecklistDetailView,
    DocumentChecklistFromTemplateView,
    DocumentChecklistItemCreateView,
    DocumentChecklistItemDetailView,
    DocumentChecklistListCreateView,
    DocumentExtractionApplyView,
    DocumentExtractionDetailView,
    DocumentExtractionListCreateView,
    DocumentExportDetailView,
    DocumentExportDownloadView,
    DocumentExportListCreateView,
    DocumentFileCreateVersionView,
    DocumentFileActivityView,
    DocumentFileDetailView,
    DocumentFileDownloadView,
    DocumentFileListCreateView,
    DocumentFilePermanentDeleteView,
    DocumentFilePreviewView,
    DocumentFileRestoreView,
    DocumentFileShareLinkDetailView,
    DocumentFileShareLinkListCreateView,
    DocumentFileShareLinkRevokeView,
    DocumentFileTrashListView,
    DocumentFileTrashView,
    AiBriefingView,
    DocumentFileFillSignView,
    FileIntakeView,
    GeneratedDocumentDetailView,
    GeneratedDocumentListCreateView,
    PreparedDocumentListView,
    AiChatView,
    DocumentDraftView,
    DocumentProofRecordListView,
    DocumentQAView,
    DocumentAIIndexView,
    DocumentAIIndexStatusView,
    PackCopilotView,
    PackCopilotCreateBundleView,
    FileInboxAttachDocumentView,
    DocumentCategoryDetailView,
    DocumentCategoryListView,
    FileInboxCreateDocumentView,
    FileInboxDetailView,
    FileInboxDownloadView,
    FileInboxDuplicateCheckView,
    FileInboxListCreateView,
    FileInboxPermanentDeleteView,
    FileInboxPreviewView,
    FileInboxRestoreView,
    FileInboxTrashListView,
    DocumentReminderRuleDetailView,
    DocumentReminderRuleListCreateView,
    DocumentTimelineView,
    DocumentVersionDetailView,
    DocumentVersionListView,
    DocumentVersionRestoreMetadataView,
    DocumentViewSet,
    EmergencyPackViewSet,
    LifeRadarView,
    PlanUsageView,
    ProofRecordViewSet,
    PublicEmergencyPackItemDownloadView,
    PublicEmergencyPackItemPreviewView,
    PublicEmergencyPackMetadataView,
    PublicEmergencyPackVerifyCodeView,
    PublicEmergencyUnlockRequestCreateView,
    PublicEmergencyUnlockRequestStatusView,
    PublicSharedFileDownloadView,
    PublicSharedFileMetadataView,
    PublicSharedFilePreviewView,
    PublicSharedFileVerifyCodeView,
    UpcomingDocumentRemindersView,
)

router = DefaultRouter()
router.register("documents", DocumentViewSet, basename="document")
router.register("emergency-packs", EmergencyPackViewSet, basename="emergency-pack")
router.register("proof-records", ProofRecordViewSet, basename="proof-record")
router.register("document-tags", DocumentTagViewSet, basename="document-tag")
router.register("appointments", DocumentAppointmentViewSet, basename="appointment")
router.register("payments", DocumentPaymentViewSet, basename="payment")

# Owner endpoints for files, previews, share links, and activity. Listed before
# the router so the more specific paths are matched first.
file_base = "documents/<int:document_id>/files"

urlpatterns = [
    path(
        "document-categories/",
        DocumentCategoryListView.as_view(),
        name="document-categories",
    ),
    path(
        "document-categories/<int:pk>/",
        DocumentCategoryDetailView.as_view(),
        name="document-category-detail",
    ),
    path(
        "scanner/upload-scanned-document/",
        UploadScannedDocumentView.as_view(),
        name="upload_scanned_document",
    ),
    path("files/", FileInboxListCreateView.as_view(), name="file-inbox"),
    path(
        "files/check-duplicate/",
        FileInboxDuplicateCheckView.as_view(),
        name="file-inbox-check-duplicate",
    ),
    path("files/trash/", FileInboxTrashListView.as_view(), name="file-inbox-trash"),
    path("files/<int:pk>/", FileInboxDetailView.as_view(), name="file-inbox-detail"),
    path(
        "files/<int:pk>/download/",
        FileInboxDownloadView.as_view(),
        name="file-inbox-download",
    ),
    path(
        "files/<int:pk>/preview/",
        FileInboxPreviewView.as_view(),
        name="file-inbox-preview",
    ),
    path(
        "files/<int:pk>/restore/",
        FileInboxRestoreView.as_view(),
        name="file-inbox-restore",
    ),
    path(
        "files/<int:pk>/permanent-delete/",
        FileInboxPermanentDeleteView.as_view(),
        name="file-inbox-permanent-delete",
    ),
    path(
        "files/<int:pk>/intake/",
        FileIntakeView.as_view(),
        name="file-inbox-intake",
    ),
    path(
        "files/<int:pk>/fill-sign/",
        DocumentFileFillSignView.as_view(),
        name="file-fill-sign",
    ),
    path(
        "fill-sign/prepared/",
        PreparedDocumentListView.as_view(),
        name="fill-sign-prepared",
    ),
    path(
        "generated-documents/",
        GeneratedDocumentListCreateView.as_view(),
        name="generated-documents",
    ),
    path(
        "generated-documents/<int:pk>/",
        GeneratedDocumentDetailView.as_view(),
        name="generated-document-detail",
    ),
    path(
        "files/<int:pk>/attach-document/",
        FileInboxAttachDocumentView.as_view(),
        name="file-inbox-attach-document",
    ),
    path(
        "files/<int:pk>/create-document/",
        FileInboxCreateDocumentView.as_view(),
        name="file-inbox-create-document",
    ),
    path(
        f"{file_base}/",
        DocumentFileListCreateView.as_view(),
        name="document-files",
    ),
    path(
        f"{file_base}/trash/",
        DocumentFileTrashListView.as_view(),
        name="document-file-trash-list",
    ),
    path(
        f"{file_base}/<int:pk>/",
        DocumentFileDetailView.as_view(),
        name="document-file-detail",
    ),
    path(
        f"{file_base}/<int:pk>/download/",
        DocumentFileDownloadView.as_view(),
        name="document-file-download",
    ),
    path(
        f"{file_base}/<int:pk>/preview/",
        DocumentFilePreviewView.as_view(),
        name="document-file-preview",
    ),
    path(
        "documents/files/export-selected/",
        DocumentFilesExportSelectedView.as_view(),
        name="documents-files-export-selected",
    ),
    path(
        "documents/export-documents/",
        DocumentsBulkExportView.as_view(),
        name="documents-bulk-export",
    ),
    path(
        f"{file_base}/<int:file_id>/trash/",
        DocumentFileTrashView.as_view(),
        name="document-file-trash",
    ),
    path(
        f"{file_base}/<int:file_id>/restore/",
        DocumentFileRestoreView.as_view(),
        name="document-file-restore",
    ),
    path(
        f"{file_base}/<int:file_id>/permanent-delete/",
        DocumentFilePermanentDeleteView.as_view(),
        name="document-file-permanent-delete",
    ),
    path(
        f"{file_base}/<int:file_id>/versions/",
        DocumentFileCreateVersionView.as_view(),
        name="document-file-create-version",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/",
        DocumentFileShareLinkListCreateView.as_view(),
        name="document-file-share-links",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/<int:share_id>/",
        DocumentFileShareLinkDetailView.as_view(),
        name="document-file-share-link-detail",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/<int:share_id>/revoke/",
        DocumentFileShareLinkRevokeView.as_view(),
        name="document-file-share-link-revoke",
    ),
    path(
        f"{file_base}/<int:file_id>/activity/",
        DocumentFileActivityView.as_view(),
        name="document-file-activity",
    ),
    path(
        "documents/<int:document_id>/versions/",
        DocumentVersionListView.as_view(),
        name="document-versions",
    ),
    path(
        "documents/<int:document_id>/versions/<int:version_id>/",
        DocumentVersionDetailView.as_view(),
        name="document-version-detail",
    ),
    path(
        "documents/<int:document_id>/versions/<int:version_id>/restore-metadata/",
        DocumentVersionRestoreMetadataView.as_view(),
        name="document-version-restore-metadata",
    ),
    path(
        "documents/<int:document_id>/activity/",
        DocumentActivityTimelineView.as_view(),
        name="document-activity",
    ),
    path(
        "documents/<int:document_id>/proof-records/",
        DocumentProofRecordListView.as_view(),
        name="document-proof-records",
    ),
    path(
        "document-bundles/<int:bundle_id>/proof-records/",
        BundleProofRecordListView.as_view(),
        name="bundle-proof-records",
    ),
    path(
        "document-exports/",
        DocumentExportListCreateView.as_view(),
        name="document-exports",
    ),
    path(
        "document-exports/<int:export_id>/",
        DocumentExportDetailView.as_view(),
        name="document-export-detail",
    ),
    path(
        "document-exports/<int:export_id>/download/",
        DocumentExportDownloadView.as_view(),
        name="document-export-download",
    ),
    path(
        "documents/reminders/upcoming/",
        UpcomingDocumentRemindersView.as_view(),
        name="document-reminders-upcoming",
    ),
    # ---- Plan limits foundation: read-only plan + usage snapshot -----------
    path(
        "plan/usage/",
        PlanUsageView.as_view(),
        name="plan-usage",
    ),
    # ---- Life Radar V1: deterministic readiness dashboard (no AI) ----------
    path(
        "documents/life-radar/",
        LifeRadarView.as_view(),
        name="life-radar",
    ),
    # ---- Intelligence polish: scanners over the whole vault ----------------
    path(
        "documents/missing-summary/",
        DocumentMissingScanView.as_view(),
        name="document-missing-summary",
    ),
    path(
        "documents/health-overview/",
        DocumentHealthOverviewView.as_view(),
        name="document-health-overview",
    ),
    # ---- AI: "ask your documents" (grounded Q&A; opt-in, key+flag gated) ----
    path(
        "documents/ask/",
        DocumentQAView.as_view(),
        name="document-ask",
    ),
    # ---- AI: chunk-level RAG indexing (manual; opt-in, key+flag gated) ----
    path(
        "documents/<int:pk>/ai/index/",
        DocumentAIIndexView.as_view(),
        name="document-ai-index",
    ),
    path(
        "documents/<int:pk>/ai/index-status/",
        DocumentAIIndexStatusView.as_view(),
        name="document-ai-index-status",
    ),
    # ---- AI: drafting assistant (letters/emails; opt-in, key+flag gated) ----
    path(
        "documents/draft/",
        DocumentDraftView.as_view(),
        name="document-draft",
    ),
    # ---- AI: application pack copilot (goal -> gap analysis; opt-in) --------
    path(
        "documents/pack-copilot/",
        PackCopilotView.as_view(),
        name="document-pack-copilot",
    ),
    path(
        "documents/pack-copilot/create-bundle/",
        PackCopilotCreateBundleView.as_view(),
        name="document-pack-copilot-create-bundle",
    ),
    # ---- AI: proactive briefing (what to do now; opt-in, key+flag gated) ----
    path(
        "documents/ai-briefing/",
        AiBriefingView.as_view(),
        name="document-ai-briefing",
    ),
    path(
        "documents/ai-chat/",
        AiChatView.as_view(),
        name="document-ai-chat",
    ),
    # ---- Intelligence polish: renewal history (nested under a document) ----
    path(
        "documents/<int:document_id>/renewal-events/",
        DocumentRenewalEventListCreateView.as_view(),
        name="document-renewal-events",
    ),
    path(
        "documents/<int:document_id>/renewal-events/<int:event_id>/",
        DocumentRenewalEventDetailView.as_view(),
        name="document-renewal-event-detail",
    ),
    path(
        "documents/<int:document_id>/reminder-rules/",
        DocumentReminderRuleListCreateView.as_view(),
        name="document-reminder-rules",
    ),
    path(
        "documents/<int:document_id>/reminder-rules/<int:rule_id>/",
        DocumentReminderRuleDetailView.as_view(),
        name="document-reminder-rule-detail",
    ),
    # ---- Renewal workspace: checklist templates (shared, read-only) --------
    path(
        "documents/checklist-templates/",
        ChecklistTemplateListView.as_view(),
        name="checklist-templates",
    ),
    path(
        "documents/checklist-templates/<int:template_id>/",
        ChecklistTemplateDetailView.as_view(),
        name="checklist-template-detail",
    ),
    # ---- Renewal workspace: timeline ---------------------------------------
    path(
        "documents/timeline/",
        DocumentTimelineView.as_view(),
        name="document-timeline",
    ),
    # ---- Renewal workspace: user checklists (nested under a document) ------
    path(
        "documents/<int:document_id>/checklists/",
        DocumentChecklistListCreateView.as_view(),
        name="document-checklists",
    ),
    path(
        "documents/<int:document_id>/checklists/from-template/",
        DocumentChecklistFromTemplateView.as_view(),
        name="document-checklist-from-template",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/",
        DocumentChecklistDetailView.as_view(),
        name="document-checklist-detail",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/items/",
        DocumentChecklistItemCreateView.as_view(),
        name="document-checklist-items",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/items/<int:item_id>/",
        DocumentChecklistItemDetailView.as_view(),
        name="document-checklist-item-detail",
    ),
    # ---- Renewal workspace: OCR-assisted extraction (nested under a file) --
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/",
        DocumentExtractionListCreateView.as_view(),
        name="document-file-extractions",
    ),
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/<int:extraction_id>/",
        DocumentExtractionDetailView.as_view(),
        name="document-file-extraction-detail",
    ),
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/<int:extraction_id>/apply/",
        DocumentExtractionApplyView.as_view(),
        name="document-file-extraction-apply",
    ),
    # ---- Renewal workspace: application / renewal bundles ------------------
    path(
        "document-bundles/pack-templates/",
        PackTemplatesView.as_view(),
        name="pack-templates",
    ),
    # ---- Application Tracker V1 -------------------------------------------
    path(
        "applications/",
        ApplicationListCreateView.as_view(),
        name="applications",
    ),
    path(
        "applications/summary/",
        ApplicationSummaryView.as_view(),
        name="applications-summary",
    ),
    path(
        "applications/<int:application_id>/",
        ApplicationDetailView.as_view(),
        name="application-detail",
    ),
    # ---- AI Application Document Generator V1 -----------------------------
    # Distinct `application-documents/` prefix — the legacy `generated-documents/`
    # routes belong to the older text-draft GeneratedDocument feature.
    path(
        "application-documents/templates/",
        ApplicationDocumentTemplatesView.as_view(),
        name="application-documents-templates",
    ),
    path(
        "application-documents/generate/",
        ApplicationDocumentGenerateView.as_view(),
        name="application-documents-generate",
    ),
    path(
        "application-documents/<int:pk>/",
        ApplicationDocumentDetailView.as_view(),
        name="application-document-detail",
    ),
    path(
        "application-documents/<int:pk>/export/",
        ApplicationDocumentExportView.as_view(),
        name="application-document-export",
    ),
    path(
        "application-documents/<int:pk>/save-to-pack/",
        ApplicationDocumentSaveToPackView.as_view(),
        name="application-document-save-to-pack",
    ),
    # Magic Inbox V1 — capture -> analyze -> review -> apply. Owner-scoped.
    path(
        "magic-inbox/",
        MagicInboxListCreateView.as_view(),
        name="magic-inbox-list-create",
    ),
    path(
        "magic-inbox/<int:pk>/",
        MagicInboxDetailView.as_view(),
        name="magic-inbox-detail",
    ),
    path(
        "magic-inbox/<int:pk>/analyze/",
        MagicInboxAnalyzeView.as_view(),
        name="magic-inbox-analyze",
    ),
    path(
        "magic-inbox/<int:pk>/apply/",
        MagicInboxApplyView.as_view(),
        name="magic-inbox-apply",
    ),
    path(
        "magic-inbox/<int:pk>/archive/",
        MagicInboxArchiveView.as_view(),
        name="magic-inbox-archive",
    ),
    # Document Request Links V1 — request -> upload -> review -> attach. Owner-scoped.
    path(
        "document-requests/",
        DocumentRequestListCreateView.as_view(),
        name="document-requests",
    ),
    path(
        "document-requests/<int:pk>/",
        DocumentRequestDetailView.as_view(),
        name="document-request-detail",
    ),
    path(
        "document-requests/<int:pk>/send/",
        DocumentRequestSendView.as_view(),
        name="document-request-send",
    ),
    path(
        "document-requests/<int:pk>/cancel/",
        DocumentRequestCancelView.as_view(),
        name="document-request-cancel",
    ),
    path(
        "document-requests/<int:pk>/review/",
        DocumentRequestReviewView.as_view(),
        name="document-request-review",
    ),
    path(
        "document-requests/<int:pk>/accept/",
        DocumentRequestAcceptView.as_view(),
        name="document-request-accept",
    ),
    path(
        "document-requests/<int:pk>/reject/",
        DocumentRequestRejectView.as_view(),
        name="document-request-reject",
    ),
    path(
        "document-requests/<int:pk>/needs-replacement/",
        DocumentRequestNeedsReplacementView.as_view(),
        name="document-request-needs-replacement",
    ),
    path(
        "document-requests/<int:pk>/save-to-vault/",
        DocumentRequestSaveToVaultView.as_view(),
        name="document-request-save-to-vault",
    ),
    path(
        "document-requests/<int:pk>/attach-to-pack/",
        DocumentRequestAttachToPackView.as_view(),
        name="document-request-attach-to-pack",
    ),
    # Public recipient routes (no auth — token only). Distinct prefix from the
    # organizations app's ``public/document-requests/`` portal routes to avoid a
    # URL collision (documents is included before organizations in config/urls).
    path(
        "public/document-request-links/<str:token>/",
        PublicDocumentRequestMetadataView.as_view(),
        name="public-document-request-link",
    ),
    path(
        "public/document-request-links/<str:token>/upload/",
        PublicDocumentRequestUploadView.as_view(),
        name="public-document-request-link-upload",
    ),
    # Sharing Rooms V1 — secure workspaces around a pack/application. Owner-scoped.
    path(
        "sharing-rooms/",
        SharingRoomListCreateView.as_view(),
        name="sharing-rooms",
    ),
    path(
        "sharing-rooms/from-pack/<int:bundle_id>/",
        SharingRoomFromPackView.as_view(),
        name="sharing-room-from-pack",
    ),
    path(
        "sharing-rooms/from-application/<int:application_id>/",
        SharingRoomFromApplicationView.as_view(),
        name="sharing-room-from-application",
    ),
    path(
        "sharing-rooms/<int:pk>/",
        SharingRoomDetailView.as_view(),
        name="sharing-room-detail",
    ),
    path(
        "sharing-rooms/<int:pk>/add-item/",
        SharingRoomAddItemView.as_view(),
        name="sharing-room-add-item",
    ),
    path(
        "sharing-rooms/<int:pk>/remove-item/",
        SharingRoomRemoveItemView.as_view(),
        name="sharing-room-remove-item",
    ),
    path(
        "sharing-rooms/<int:pk>/revoke/",
        SharingRoomRevokeView.as_view(),
        name="sharing-room-revoke",
    ),
    path(
        "sharing-rooms/<int:pk>/archive/",
        SharingRoomArchiveView.as_view(),
        name="sharing-room-archive",
    ),
    # Public recipient routes (no auth — token only). Distinct from the older
    # ShareRoom ``public/rooms/`` routes.
    path(
        "public/sharing-rooms/<str:token>/",
        PublicSharingRoomMetadataView.as_view(),
        name="public-sharing-room",
    ),
    path(
        "public/sharing-rooms/<str:token>/files/<int:file_id>/preview/",
        PublicSharingRoomFilePreviewView.as_view(),
        name="public-sharing-room-file-preview",
    ),
    path(
        "public/sharing-rooms/<str:token>/files/<int:file_id>/download/",
        PublicSharingRoomFileDownloadView.as_view(),
        name="public-sharing-room-file-download",
    ),
    # Redaction + Watermarking V1 — protected copies. Owner-scoped; no public route
    # (protected files are shared through Sharing Rooms / private download only).
    path(
        "protected-copies/",
        ProtectedCopyListCreateView.as_view(),
        name="protected-copies",
    ),
    path(
        "protected-copies/<int:pk>/",
        ProtectedCopyDetailView.as_view(),
        name="protected-copy-detail",
    ),
    path(
        "protected-copies/<int:pk>/generate/",
        ProtectedCopyGenerateView.as_view(),
        name="protected-copy-generate",
    ),
    path(
        "protected-copies/<int:pk>/archive/",
        ProtectedCopyArchiveView.as_view(),
        name="protected-copy-archive",
    ),
    path(
        "protected-copies/<int:pk>/add-to-room/",
        ProtectedCopyAddToRoomView.as_view(),
        name="protected-copy-add-to-room",
    ),
    # Audit Logs V1 — owner-scoped security/document event history.
    path(
        "audit-logs/",
        AuditLogListView.as_view(),
        name="audit-logs",
    ),
    path(
        "audit-logs/summary/",
        AuditLogSummaryView.as_view(),
        name="audit-logs-summary",
    ),
    path(
        "audit-logs/<int:pk>/",
        AuditLogDetailView.as_view(),
        name="audit-log-detail",
    ),
    path(
        "document-bundles/",
        DocumentBundleListCreateView.as_view(),
        name="document-bundles",
    ),
    # Pack Readiness V1 summary across the user's active packs (static segment
    # before the <int:bundle_id> routes so it is never captured as an id).
    path(
        "document-bundles/readiness-summary/",
        BundleReadinessSummaryView.as_view(),
        name="document-bundle-readiness-summary",
    ),
    path(
        "document-bundles/<int:bundle_id>/",
        DocumentBundleDetailView.as_view(),
        name="document-bundle-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/activity/",
        BundleActivityTimelineView.as_view(),
        name="document-bundle-activity",
    ),
    path(
        "document-bundles/<int:bundle_id>/readiness/",
        BundleReadinessView.as_view(),
        name="document-bundle-readiness",
    ),
    path(
        "document-bundles/<int:bundle_id>/share-readiness/",
        BundleShareReadinessView.as_view(),
        name="document-bundle-share-readiness",
    ),
    path(
        "document-bundles/<int:bundle_id>/files/",
        DocumentBundleFilesView.as_view(),
        name="document-bundle-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/export-files/",
        DocumentBundleExportFilesView.as_view(),
        name="document-bundle-export-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/export-selected-files/",
        DocumentBundleExportSelectedFilesView.as_view(),
        name="document-bundle-export-selected-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/export-merged-pdf/",
        DocumentBundleExportMergedPdfView.as_view(),
        name="document-bundle-export-merged-pdf",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/",
        BundleExportListCreateView.as_view(),
        name="document-bundle-exports",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/<int:export_id>/",
        BundleExportDetailView.as_view(),
        name="document-bundle-export-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/<int:export_id>/download/",
        BundleExportDownloadView.as_view(),
        name="document-bundle-export-download",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/",
        DocumentBundleRequirementCreateView.as_view(),
        name="document-bundle-requirements",
    ),
    # Requirement Link import (static "import-link" segments declared before the
    # <int:requirement_id> routes so they are never captured as a requirement id).
    path(
        "document-bundles/<int:bundle_id>/requirements/import-link/",
        RequirementLinkImportView.as_view(),
        name="document-bundle-requirements-import-link",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/import-link/<int:draft_id>/apply/",
        RequirementLinkImportApplyView.as_view(),
        name="document-bundle-requirements-import-link-apply",
    ),
    path(
        "document-bundles/<int:bundle_id>/add-documents/",
        BundleAddDocumentsView.as_view(),
        name="document-bundle-add-documents",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/",
        DocumentBundleRequirementDetailView.as_view(),
        name="document-bundle-requirement-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/link-document/",
        BundleRequirementLinkDocumentView.as_view(),
        name="document-bundle-requirement-link-document",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/link-file/",
        BundleRequirementLinkFileView.as_view(),
        name="document-bundle-requirement-link-file",
    ),
    # ---- Calendar V1 -------------------------------------------------------
    path(
        "calendar/events/",
        CalendarEventsView.as_view(),
        name="calendar-events",
    ),
    path(
        "calendar/summary/",
        CalendarSummaryView.as_view(),
        name="calendar-summary",
    ),
    path(
        "calendar/export.ics",
        CalendarIcsExportView.as_view(),
        name="calendar-export-ics",
    ),
    # ---- Secure rooms (owner) ----------------------------------------------
    path(
        "share-rooms/",
        ShareRoomListCreateView.as_view(),
        name="share-rooms",
    ),
    path(
        "share-rooms/<int:room_id>/",
        ShareRoomDetailView.as_view(),
        name="share-room-detail",
    ),
    path(
        "share-rooms/<int:room_id>/items/",
        ShareRoomItemsView.as_view(),
        name="share-room-items",
    ),
    path(
        "share-rooms/<int:room_id>/items/<int:item_id>/",
        ShareRoomItemDeleteView.as_view(),
        name="share-room-item-detail",
    ),
    path(
        "share-rooms/<int:room_id>/revoke/",
        ShareRoomRevokeView.as_view(),
        name="share-room-revoke",
    ),
    path(
        "share-rooms/<int:room_id>/activity/",
        ShareRoomActivityView.as_view(),
        name="share-room-activity",
    ),
    # ---- Secure rooms (public, token-gated) --------------------------------
    path(
        "public/rooms/<str:token>/",
        PublicShareRoomMetadataView.as_view(),
        name="public-room",
    ),
    path(
        "public/rooms/<str:token>/verify-code/",
        PublicShareRoomVerifyCodeView.as_view(),
        name="public-room-verify-code",
    ),
    path(
        "public/rooms/<str:token>/files/<int:file_id>/preview/",
        PublicShareRoomFilePreviewView.as_view(),
        name="public-room-file-preview",
    ),
    path(
        "public/rooms/<str:token>/files/<int:file_id>/download/",
        PublicShareRoomFileDownloadView.as_view(),
        name="public-room-file-download",
    ),
    path(
        "public/rooms/<str:token>/download-zip/",
        PublicShareRoomZipView.as_view(),
        name="public-room-download-zip",
    ),
    # Public share endpoints (token-gated, no authentication).
    path(
        "share/files/<str:token>/",
        PublicSharedFileMetadataView.as_view(),
        name="public-shared-file",
    ),
    path(
        "share/files/<str:token>/verify-code/",
        PublicSharedFileVerifyCodeView.as_view(),
        name="public-shared-file-verify-code",
    ),
    path(
        "share/files/<str:token>/preview/",
        PublicSharedFilePreviewView.as_view(),
        name="public-shared-file-preview",
    ),
    path(
        "share/files/<str:token>/download/",
        PublicSharedFileDownloadView.as_view(),
        name="public-shared-file-download",
    ),
    path(
        "share/emergency-packs/<str:token>/",
        PublicEmergencyPackMetadataView.as_view(),
        name="public-emergency-pack",
    ),
    path(
        "share/emergency-packs/<str:token>/verify-code/",
        PublicEmergencyPackVerifyCodeView.as_view(),
        name="public-emergency-pack-verify-code",
    ),
    path(
        "share/emergency-packs/<str:token>/request/",
        PublicEmergencyUnlockRequestCreateView.as_view(),
        name="public-emergency-pack-request",
    ),
    path(
        "share/emergency-packs/<str:token>/request/<str:request_token>/",
        PublicEmergencyUnlockRequestStatusView.as_view(),
        name="public-emergency-pack-request-status",
    ),
    path(
        "share/emergency-packs/<str:token>/items/<int:item_id>/preview/",
        PublicEmergencyPackItemPreviewView.as_view(),
        name="public-emergency-pack-item-preview",
    ),
    path(
        "share/emergency-packs/<str:token>/items/<int:item_id>/download/",
        PublicEmergencyPackItemDownloadView.as_view(),
        name="public-emergency-pack-item-download",
    ),
] + router.urls
