from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    BundleExportDetailView,
    BundleExportDownloadView,
    BundleExportListCreateView,
    BundleProofRecordListView,
    BundleReadinessView,
    BundleRequirementLinkDocumentView,
    BundleRequirementLinkFileView,
    ChecklistTemplateDetailView,
    ChecklistTemplateListView,
    DocumentActivityTimelineView,
    DocumentAppointmentViewSet,
    DocumentBundleDetailView,
    DocumentBundleExportFilesView,
    DocumentBundleExportSelectedFilesView,
    DocumentBundleFilesView,
    DocumentBundleListCreateView,
    CalendarEventsView,
    CalendarIcsExportView,
    CalendarSummaryView,
    DocumentFilesExportSelectedView,
    PublicShareRoomFileDownloadView,
    PublicShareRoomFilePreviewView,
    PublicShareRoomMetadataView,
    PublicShareRoomVerifyCodeView,
    PublicShareRoomZipView,
    ShareRoomActivityView,
    ShareRoomDetailView,
    ShareRoomItemDeleteView,
    ShareRoomItemsView,
    ShareRoomListCreateView,
    ShareRoomRevokeView,
    DocumentBundleRequirementCreateView,
    DocumentBundleRequirementDetailView,
    DocumentHealthOverviewView,
    DocumentMissingScanView,
    DocumentPaymentViewSet,
    DocumentRenewalEventDetailView,
    DocumentRenewalEventListCreateView,
    DocumentTagViewSet,
    DocumentChecklistDetailView,
    DocumentChecklistFromTemplateView,
    DocumentChecklistItemCreateView,
    DocumentChecklistItemDetailView,
    DocumentChecklistListCreateView,
    DocumentExtractionApplyView,
    DocumentExtractionDetailView,
    DocumentExtractionListCreateView,
    DocumentExportDetailView,
    DocumentExportDownloadView,
    DocumentExportListCreateView,
    DocumentFileCreateVersionView,
    DocumentFileActivityView,
    DocumentFileDetailView,
    DocumentFileDownloadView,
    DocumentFileListCreateView,
    DocumentFilePermanentDeleteView,
    DocumentFilePreviewView,
    DocumentFileRestoreView,
    DocumentFileShareLinkDetailView,
    DocumentFileShareLinkListCreateView,
    DocumentFileShareLinkRevokeView,
    DocumentFileTrashListView,
    DocumentFileTrashView,
    DocumentProofRecordListView,
    FileInboxAttachDocumentView,
    DocumentCategoryListView,
    FileInboxCreateDocumentView,
    FileInboxDetailView,
    FileInboxDownloadView,
    FileInboxListCreateView,
    FileInboxPermanentDeleteView,
    FileInboxPreviewView,
    FileInboxRestoreView,
    FileInboxTrashListView,
    DocumentReminderRuleDetailView,
    DocumentReminderRuleListCreateView,
    DocumentTimelineView,
    DocumentVersionDetailView,
    DocumentVersionListView,
    DocumentVersionRestoreMetadataView,
    DocumentViewSet,
    EmergencyPackViewSet,
    PlanUsageView,
    ProofRecordViewSet,
    PublicEmergencyPackItemDownloadView,
    PublicEmergencyPackItemPreviewView,
    PublicEmergencyPackMetadataView,
    PublicEmergencyPackVerifyCodeView,
    PublicSharedFileDownloadView,
    PublicSharedFileMetadataView,
    PublicSharedFilePreviewView,
    PublicSharedFileVerifyCodeView,
    UpcomingDocumentRemindersView,
)

router = DefaultRouter()
router.register("documents", DocumentViewSet, basename="document")
router.register("emergency-packs", EmergencyPackViewSet, basename="emergency-pack")
router.register("proof-records", ProofRecordViewSet, basename="proof-record")
router.register("document-tags", DocumentTagViewSet, basename="document-tag")
router.register("appointments", DocumentAppointmentViewSet, basename="appointment")
router.register("payments", DocumentPaymentViewSet, basename="payment")

# Owner endpoints for files, previews, share links, and activity. Listed before
# the router so the more specific paths are matched first.
file_base = "documents/<int:document_id>/files"

urlpatterns = [
    path(
        "document-categories/",
        DocumentCategoryListView.as_view(),
        name="document-categories",
    ),
    path("files/", FileInboxListCreateView.as_view(), name="file-inbox"),
    path("files/trash/", FileInboxTrashListView.as_view(), name="file-inbox-trash"),
    path("files/<int:pk>/", FileInboxDetailView.as_view(), name="file-inbox-detail"),
    path(
        "files/<int:pk>/download/",
        FileInboxDownloadView.as_view(),
        name="file-inbox-download",
    ),
    path(
        "files/<int:pk>/preview/",
        FileInboxPreviewView.as_view(),
        name="file-inbox-preview",
    ),
    path(
        "files/<int:pk>/restore/",
        FileInboxRestoreView.as_view(),
        name="file-inbox-restore",
    ),
    path(
        "files/<int:pk>/permanent-delete/",
        FileInboxPermanentDeleteView.as_view(),
        name="file-inbox-permanent-delete",
    ),
    path(
        "files/<int:pk>/attach-document/",
        FileInboxAttachDocumentView.as_view(),
        name="file-inbox-attach-document",
    ),
    path(
        "files/<int:pk>/create-document/",
        FileInboxCreateDocumentView.as_view(),
        name="file-inbox-create-document",
    ),
    path(
        f"{file_base}/",
        DocumentFileListCreateView.as_view(),
        name="document-files",
    ),
    path(
        f"{file_base}/trash/",
        DocumentFileTrashListView.as_view(),
        name="document-file-trash-list",
    ),
    path(
        f"{file_base}/<int:pk>/",
        DocumentFileDetailView.as_view(),
        name="document-file-detail",
    ),
    path(
        f"{file_base}/<int:pk>/download/",
        DocumentFileDownloadView.as_view(),
        name="document-file-download",
    ),
    path(
        f"{file_base}/<int:pk>/preview/",
        DocumentFilePreviewView.as_view(),
        name="document-file-preview",
    ),
    path(
        "documents/files/export-selected/",
        DocumentFilesExportSelectedView.as_view(),
        name="documents-files-export-selected",
    ),
    path(
        f"{file_base}/<int:file_id>/trash/",
        DocumentFileTrashView.as_view(),
        name="document-file-trash",
    ),
    path(
        f"{file_base}/<int:file_id>/restore/",
        DocumentFileRestoreView.as_view(),
        name="document-file-restore",
    ),
    path(
        f"{file_base}/<int:file_id>/permanent-delete/",
        DocumentFilePermanentDeleteView.as_view(),
        name="document-file-permanent-delete",
    ),
    path(
        f"{file_base}/<int:file_id>/versions/",
        DocumentFileCreateVersionView.as_view(),
        name="document-file-create-version",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/",
        DocumentFileShareLinkListCreateView.as_view(),
        name="document-file-share-links",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/<int:share_id>/",
        DocumentFileShareLinkDetailView.as_view(),
        name="document-file-share-link-detail",
    ),
    path(
        f"{file_base}/<int:file_id>/share-links/<int:share_id>/revoke/",
        DocumentFileShareLinkRevokeView.as_view(),
        name="document-file-share-link-revoke",
    ),
    path(
        f"{file_base}/<int:file_id>/activity/",
        DocumentFileActivityView.as_view(),
        name="document-file-activity",
    ),
    path(
        "documents/<int:document_id>/versions/",
        DocumentVersionListView.as_view(),
        name="document-versions",
    ),
    path(
        "documents/<int:document_id>/versions/<int:version_id>/",
        DocumentVersionDetailView.as_view(),
        name="document-version-detail",
    ),
    path(
        "documents/<int:document_id>/versions/<int:version_id>/restore-metadata/",
        DocumentVersionRestoreMetadataView.as_view(),
        name="document-version-restore-metadata",
    ),
    path(
        "documents/<int:document_id>/activity/",
        DocumentActivityTimelineView.as_view(),
        name="document-activity",
    ),
    path(
        "documents/<int:document_id>/proof-records/",
        DocumentProofRecordListView.as_view(),
        name="document-proof-records",
    ),
    path(
        "document-bundles/<int:bundle_id>/proof-records/",
        BundleProofRecordListView.as_view(),
        name="bundle-proof-records",
    ),
    path(
        "document-exports/",
        DocumentExportListCreateView.as_view(),
        name="document-exports",
    ),
    path(
        "document-exports/<int:export_id>/",
        DocumentExportDetailView.as_view(),
        name="document-export-detail",
    ),
    path(
        "document-exports/<int:export_id>/download/",
        DocumentExportDownloadView.as_view(),
        name="document-export-download",
    ),
    path(
        "documents/reminders/upcoming/",
        UpcomingDocumentRemindersView.as_view(),
        name="document-reminders-upcoming",
    ),
    # ---- Plan limits foundation: read-only plan + usage snapshot -----------
    path(
        "plan/usage/",
        PlanUsageView.as_view(),
        name="plan-usage",
    ),
    # ---- Intelligence polish: scanners over the whole vault ----------------
    path(
        "documents/missing-summary/",
        DocumentMissingScanView.as_view(),
        name="document-missing-summary",
    ),
    path(
        "documents/health-overview/",
        DocumentHealthOverviewView.as_view(),
        name="document-health-overview",
    ),
    # ---- Intelligence polish: renewal history (nested under a document) ----
    path(
        "documents/<int:document_id>/renewal-events/",
        DocumentRenewalEventListCreateView.as_view(),
        name="document-renewal-events",
    ),
    path(
        "documents/<int:document_id>/renewal-events/<int:event_id>/",
        DocumentRenewalEventDetailView.as_view(),
        name="document-renewal-event-detail",
    ),
    path(
        "documents/<int:document_id>/reminder-rules/",
        DocumentReminderRuleListCreateView.as_view(),
        name="document-reminder-rules",
    ),
    path(
        "documents/<int:document_id>/reminder-rules/<int:rule_id>/",
        DocumentReminderRuleDetailView.as_view(),
        name="document-reminder-rule-detail",
    ),
    # ---- Renewal workspace: checklist templates (shared, read-only) --------
    path(
        "documents/checklist-templates/",
        ChecklistTemplateListView.as_view(),
        name="checklist-templates",
    ),
    path(
        "documents/checklist-templates/<int:template_id>/",
        ChecklistTemplateDetailView.as_view(),
        name="checklist-template-detail",
    ),
    # ---- Renewal workspace: timeline ---------------------------------------
    path(
        "documents/timeline/",
        DocumentTimelineView.as_view(),
        name="document-timeline",
    ),
    # ---- Renewal workspace: user checklists (nested under a document) ------
    path(
        "documents/<int:document_id>/checklists/",
        DocumentChecklistListCreateView.as_view(),
        name="document-checklists",
    ),
    path(
        "documents/<int:document_id>/checklists/from-template/",
        DocumentChecklistFromTemplateView.as_view(),
        name="document-checklist-from-template",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/",
        DocumentChecklistDetailView.as_view(),
        name="document-checklist-detail",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/items/",
        DocumentChecklistItemCreateView.as_view(),
        name="document-checklist-items",
    ),
    path(
        "documents/<int:document_id>/checklists/<int:checklist_id>/items/<int:item_id>/",
        DocumentChecklistItemDetailView.as_view(),
        name="document-checklist-item-detail",
    ),
    # ---- Renewal workspace: OCR-assisted extraction (nested under a file) --
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/",
        DocumentExtractionListCreateView.as_view(),
        name="document-file-extractions",
    ),
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/<int:extraction_id>/",
        DocumentExtractionDetailView.as_view(),
        name="document-file-extraction-detail",
    ),
    path(
        "documents/<int:document_id>/files/<int:file_id>/extractions/<int:extraction_id>/apply/",
        DocumentExtractionApplyView.as_view(),
        name="document-file-extraction-apply",
    ),
    # ---- Renewal workspace: application / renewal bundles ------------------
    path(
        "document-bundles/",
        DocumentBundleListCreateView.as_view(),
        name="document-bundles",
    ),
    path(
        "document-bundles/<int:bundle_id>/",
        DocumentBundleDetailView.as_view(),
        name="document-bundle-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/readiness/",
        BundleReadinessView.as_view(),
        name="document-bundle-readiness",
    ),
    path(
        "document-bundles/<int:bundle_id>/files/",
        DocumentBundleFilesView.as_view(),
        name="document-bundle-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/export-files/",
        DocumentBundleExportFilesView.as_view(),
        name="document-bundle-export-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/export-selected-files/",
        DocumentBundleExportSelectedFilesView.as_view(),
        name="document-bundle-export-selected-files",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/",
        BundleExportListCreateView.as_view(),
        name="document-bundle-exports",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/<int:export_id>/",
        BundleExportDetailView.as_view(),
        name="document-bundle-export-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/exports/<int:export_id>/download/",
        BundleExportDownloadView.as_view(),
        name="document-bundle-export-download",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/",
        DocumentBundleRequirementCreateView.as_view(),
        name="document-bundle-requirements",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/",
        DocumentBundleRequirementDetailView.as_view(),
        name="document-bundle-requirement-detail",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/link-document/",
        BundleRequirementLinkDocumentView.as_view(),
        name="document-bundle-requirement-link-document",
    ),
    path(
        "document-bundles/<int:bundle_id>/requirements/<int:requirement_id>/link-file/",
        BundleRequirementLinkFileView.as_view(),
        name="document-bundle-requirement-link-file",
    ),
    # ---- Calendar V1 -------------------------------------------------------
    path(
        "calendar/events/",
        CalendarEventsView.as_view(),
        name="calendar-events",
    ),
    path(
        "calendar/summary/",
        CalendarSummaryView.as_view(),
        name="calendar-summary",
    ),
    path(
        "calendar/export.ics",
        CalendarIcsExportView.as_view(),
        name="calendar-export-ics",
    ),
    # ---- Secure rooms (owner) ----------------------------------------------
    path(
        "share-rooms/",
        ShareRoomListCreateView.as_view(),
        name="share-rooms",
    ),
    path(
        "share-rooms/<int:room_id>/",
        ShareRoomDetailView.as_view(),
        name="share-room-detail",
    ),
    path(
        "share-rooms/<int:room_id>/items/",
        ShareRoomItemsView.as_view(),
        name="share-room-items",
    ),
    path(
        "share-rooms/<int:room_id>/items/<int:item_id>/",
        ShareRoomItemDeleteView.as_view(),
        name="share-room-item-detail",
    ),
    path(
        "share-rooms/<int:room_id>/revoke/",
        ShareRoomRevokeView.as_view(),
        name="share-room-revoke",
    ),
    path(
        "share-rooms/<int:room_id>/activity/",
        ShareRoomActivityView.as_view(),
        name="share-room-activity",
    ),
    # ---- Secure rooms (public, token-gated) --------------------------------
    path(
        "public/rooms/<str:token>/",
        PublicShareRoomMetadataView.as_view(),
        name="public-room",
    ),
    path(
        "public/rooms/<str:token>/verify-code/",
        PublicShareRoomVerifyCodeView.as_view(),
        name="public-room-verify-code",
    ),
    path(
        "public/rooms/<str:token>/files/<int:file_id>/preview/",
        PublicShareRoomFilePreviewView.as_view(),
        name="public-room-file-preview",
    ),
    path(
        "public/rooms/<str:token>/files/<int:file_id>/download/",
        PublicShareRoomFileDownloadView.as_view(),
        name="public-room-file-download",
    ),
    path(
        "public/rooms/<str:token>/download-zip/",
        PublicShareRoomZipView.as_view(),
        name="public-room-download-zip",
    ),
    # Public share endpoints (token-gated, no authentication).
    path(
        "share/files/<str:token>/",
        PublicSharedFileMetadataView.as_view(),
        name="public-shared-file",
    ),
    path(
        "share/files/<str:token>/verify-code/",
        PublicSharedFileVerifyCodeView.as_view(),
        name="public-shared-file-verify-code",
    ),
    path(
        "share/files/<str:token>/preview/",
        PublicSharedFilePreviewView.as_view(),
        name="public-shared-file-preview",
    ),
    path(
        "share/files/<str:token>/download/",
        PublicSharedFileDownloadView.as_view(),
        name="public-shared-file-download",
    ),
    path(
        "share/emergency-packs/<str:token>/",
        PublicEmergencyPackMetadataView.as_view(),
        name="public-emergency-pack",
    ),
    path(
        "share/emergency-packs/<str:token>/verify-code/",
        PublicEmergencyPackVerifyCodeView.as_view(),
        name="public-emergency-pack-verify-code",
    ),
    path(
        "share/emergency-packs/<str:token>/items/<int:item_id>/preview/",
        PublicEmergencyPackItemPreviewView.as_view(),
        name="public-emergency-pack-item-preview",
    ),
    path(
        "share/emergency-packs/<str:token>/items/<int:item_id>/download/",
        PublicEmergencyPackItemDownloadView.as_view(),
        name="public-emergency-pack-item-download",
    ),
] + router.urls
