# Generated by Django 5.2.15 on 2026-06-14 02:50

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0012_shareroom_roomactivity_shareroomitem_and_more'),
        ('organizations', '0002_seed_request_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickShareSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('mode', models.CharField(choices=[('account_to_account', 'Account to account'), ('public_secure_qr', 'Public secure QR'), ('emergency_qr', 'Emergency QR'), ('organization_collection', 'Organization collection')], default='account_to_account', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('permission', models.CharField(choices=[('view_only', 'View only'), ('download_allowed', 'Allow download'), ('save_copy_allowed', 'Allow save copy')], default='view_only', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('consumed', 'Consumed')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_required', models.BooleanField(default=False)),
                ('access_code_hash', models.CharField(blank=True, max_length=255)),
                ('one_time', models.BooleanField(default=False)),
                ('max_claims', models.PositiveIntegerField(blank=True, null=True)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('require_sender_approval', models.BooleanField(default=False)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_sessions', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_items', to='documents.document')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_items', to='documents.documentfile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quick_share.quicksharesession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickShareClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approval', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Awaiting sender approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_required', max_length=20)),
                ('removed_by_receiver', models.BooleanField(default=False)),
                ('user_agent_summary', models.CharField(blank=True, max_length=120)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_claims', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='quick_share.quicksharesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickShareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_created', 'Quick Share created'), ('qr_viewed', 'QR opened'), ('claim_started', 'Claim started'), ('claim_accepted', 'Claim accepted'), ('claim_declined', 'Claim declined'), ('sender_approved', 'Sender approved'), ('sender_denied', 'Sender denied'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('copy_saved', 'Copy saved to vault'), ('session_revoked', 'Quick Share revoked'), ('session_expired', 'Quick Share expired'), ('access_code_verified', 'Access code verified'), ('access_code_failed', 'Access code failed')], max_length=40)),
                ('actor_type', models.CharField(choices=[('owner', 'Owner'), ('receiver', 'Receiver'), ('system', 'System')], max_length=20)),
                ('safe_summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_share_activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='quick_share.quicksharesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quicksharesession',
            index=models.Index(fields=['owner', 'created_at'], name='quick_share_owner_i_afa4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksharesession',
            index=models.Index(fields=['token'], name='quick_share_token_86fd9c_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksharesession',
            index=models.Index(fields=['owner', 'revoked_at'], name='quick_share_owner_i_a7b7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksharesession',
            index=models.Index(fields=['expires_at'], name='quick_share_expires_e24e05_idx'),
        ),
        migrations.AddIndex(
            model_name='quickshareitem',
            index=models.Index(fields=['session', 'order'], name='quick_share_session_bd8909_idx'),
        ),
        migrations.AddIndex(
            model_name='quickshareclaim',
            index=models.Index(fields=['session', 'status'], name='quick_share_session_09bbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='quickshareclaim',
            index=models.Index(fields=['receiver_user', 'status'], name='quick_share_receive_aea52b_idx'),
        ),
        migrations.AddIndex(
            model_name='quickshareactivity',
            index=models.Index(fields=['session', 'created_at'], name='quick_share_session_524a29_idx'),
        ),
    ]
