# Generated by Django 5.2.15 on 2026-06-14 12:59

import apps.quick_share.models
from apps.quick_share.models import generate_dn_code
from django.db import migrations, models


def backfill_dn_codes(apps, schema_editor):
    """Give every existing session its own unique DueNest code."""
    QuickShareSession = apps.get_model("quick_share", "QuickShareSession")
    used = set(
        QuickShareSession.objects.exclude(dn_code="").values_list("dn_code", flat=True)
    )
    for session in QuickShareSession.objects.filter(dn_code=""):
        code = generate_dn_code()
        while code in used:
            code = generate_dn_code()
        used.add(code)
        session.dn_code = code
        session.save(update_fields=["dn_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0001_initial'),
    ]

    operations = [
        # 1) Add the column without an index or the unique constraint, with a
        #    blank default so existing rows are addressable before we generate
        #    per-row codes. No db_index here — uniqueness (step 3) supplies the
        #    index; adding db_index too makes Postgres build the varchar_pattern_ops
        #    "_like" index twice with the same name -> "already exists".
        migrations.AddField(
            model_name='quicksharesession',
            name='dn_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        # 2) Backfill a unique code for every existing session.
        migrations.RunPython(backfill_dn_codes, migrations.RunPython.noop),
        # 3) Enforce uniqueness and the callable default for new rows. unique=True
        #    creates the index (and a single "_like" index); db_index is omitted
        #    on purpose to avoid the duplicate "_like" index.
        migrations.AlterField(
            model_name='quicksharesession',
            name='dn_code',
            field=models.CharField(
                default=apps.quick_share.models.generate_dn_code,
                max_length=20,
                unique=True,
            ),
        ),
    ]
