# Generated by Django 5.2.15 on 2026-06-14 12:59

import apps.quick_share.models
from apps.quick_share.models import generate_dn_code
from django.db import migrations, models


def backfill_dn_codes(apps, schema_editor):
    """Give every existing session its own unique DueNest code."""
    QuickShareSession = apps.get_model("quick_share", "QuickShareSession")
    used = set(
        QuickShareSession.objects.exclude(dn_code="").values_list("dn_code", flat=True)
    )
    for session in QuickShareSession.objects.filter(dn_code=""):
        code = generate_dn_code()
        while code in used:
            code = generate_dn_code()
        used.add(code)
        session.dn_code = code
        session.save(update_fields=["dn_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0001_initial'),
    ]

    operations = [
        # 1) Add the column without the unique constraint and a blank default so
        #    existing rows are addressable before we generate per-row codes.
        migrations.AddField(
            model_name='quicksharesession',
            name='dn_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        # 2) Backfill a unique code for every existing session.
        migrations.RunPython(backfill_dn_codes, migrations.RunPython.noop),
        # 3) Enforce uniqueness and the callable default for new rows.
        migrations.AlterField(
            model_name='quicksharesession',
            name='dn_code',
            field=models.CharField(
                db_index=True,
                default=apps.quick_share.models.generate_dn_code,
                max_length=20,
                unique=True,
            ),
        ),
    ]
