# Generated by Django 5.2.15 on 2026-06-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_proofrecord_notes_ciphertext'),
        ('quick_share', '0002_quicksharesession_dn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickshareitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_items', to='documents.documentbundle'),
        ),
    ]
