# Generated by Django 5.2.15 on 2026-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0003_quickshareitem_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksharesession',
            name='share_method',
            field=models.CharField(choices=[('qr', 'QR code'), ('link', 'Secure link'), ('code', 'DueNest code')], default='qr', max_length=8),
        ),
    ]
