# Generated by Django 5.2.15 on 2026-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0004_quicksharesession_share_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksharesession',
            name='recipient_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
