# Generated by Django 5.2.15 on 2026-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0005_quicksharesession_recipient_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickshareactivity',
            name='action',
            field=models.CharField(choices=[('session_created', 'Quick Share created'), ('qr_viewed', 'QR opened'), ('claim_started', 'Claim started'), ('claim_accepted', 'Claim accepted'), ('claim_declined', 'Claim declined'), ('sender_approved', 'Sender approved'), ('sender_denied', 'Sender denied'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('copy_saved', 'Copy saved to vault'), ('session_revoked', 'Quick Share revoked'), ('session_expired', 'Quick Share expired'), ('session_extended', 'Quick Share extended'), ('access_code_verified', 'Access code verified'), ('access_code_failed', 'Access code failed')], max_length=40),
        ),
    ]
