# Generated by Django 5.2.15 on 2026-06-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_documentactivity_action'),
        ('quick_share', '0007_alter_quickshareactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickshareitem',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_share_items', to='documents.proofrecord'),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='privacy_screen_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
