# Generated by Django 5.2.15 on 2026-06-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0008_quickshareitem_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksharesession',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='limit_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='max_downloads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='max_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
