# Generated by Django 5.2.15 on 2026-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0009_quicksharesession_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksharesession',
            name='verification_manifest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='verification_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quicksharesession',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
