# Generated by Django 5.2.15 on 2026-06-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_share', '0010_quicksharesession_verification_manifest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksharesession',
            name='share_method',
            field=models.CharField(choices=[('qr', 'QR code'), ('link', 'Secure link'), ('code', 'CertaNest code')], default='qr', max_length=8),
        ),
    ]
