# Generated by Django 5.2.15 on 2026-06-13 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('worker', 'Worker'), ('system', 'System')], default='frontend', max_length=20)),
                ('error_type', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'created_at'], name='founder_app_severit_8cec1f_idx'), models.Index(fields=['source', 'created_at'], name='founder_app_source_c6d53f_idx'), models.Index(fields=['resolved', 'created_at'], name='founder_app_resolve_1c7689_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature request'), ('confusion', 'Confusion'), ('complaint', 'Complaint'), ('praise', 'Praise'), ('security_concern', 'Security concern'), ('pricing', 'Pricing'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('in_app', 'In app'), ('beta_form', 'Beta form'), ('founder_note', 'Founder note'), ('other', 'Other')], default='in_app', max_length=24)),
                ('related_path', models.CharField(blank=True, max_length=255)),
                ('related_feature', models.CharField(blank=True, max_length=120)),
                ('founder_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='founder_fee_status_67d4e3_idx'), models.Index(fields=['priority', 'created_at'], name='founder_fee_priorit_c8cbb7_idx'), models.Index(fields=['category', 'created_at'], name='founder_fee_categor_b61aa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_signed_up', 'User signed up'), ('user_logged_in', 'User logged in'), ('onboarding_started', 'Onboarding started'), ('onboarding_completed', 'Onboarding completed'), ('document_created', 'Document created'), ('file_uploaded', 'File uploaded'), ('expiry_date_added', 'Expiry date added'), ('reminder_created', 'Reminder created'), ('attention_needed_viewed', 'Attention needed viewed'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('bundle_created', 'Bundle created'), ('file_previewed', 'File previewed'), ('share_link_created', 'Share link created'), ('share_link_opened', 'Share link opened'), ('export_requested', 'Export requested'), ('emergency_pack_created', 'Emergency pack created'), ('proof_record_created', 'Proof record created'), ('account_deletion_requested', 'Account deletion requested'), ('feedback_submitted', 'Feedback submitted'), ('error_recorded', 'Error recorded'), ('security_event_recorded', 'Security event recorded'), ('timeline_viewed', 'Timeline viewed'), ('trash_restore_used', 'Trash restore used'), ('extraction_requested', 'Extraction requested')], max_length=64)),
                ('event_source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('system', 'System')], default='backend', max_length=20)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='founder_pro_event_t_e0caad_idx'), models.Index(fields=['user', 'created_at'], name='founder_pro_user_id_673bd3_idx'), models.Index(fields=['event_source', 'created_at'], name='founder_pro_event_s_2d97c6_idx'), models.Index(fields=['created_at'], name='founder_pro_created_b40356_idx')],
            },
        ),
    ]
