# Generated by Django 5.2.15 on 2026-06-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCompletionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('feature_name', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=80)),
                ('backend_done', models.BooleanField(default=False)),
                ('frontend_done', models.BooleanField(default=False)),
                ('tests_done', models.BooleanField(default=False)),
                ('docs_done', models.BooleanField(default=False)),
                ('polished', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('partial', 'Partial'), ('ready', 'Ready'), ('needs_polish', 'Needs polish'), ('deferred', 'Deferred')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'feature_name'],
                'indexes': [models.Index(fields=['module', 'status'], name='founder_fea_module_221427_idx'), models.Index(fields=['priority', 'status'], name='founder_fea_priorit_c19e6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LaunchChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['is_complete', 'priority'], name='founder_lau_is_comp_2a7205_idx')],
            },
        ),
        migrations.CreateModel(
            name='BetaUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('not_invited', 'Not invited'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('active', 'Active'), ('paused', 'Paused'), ('churned', 'Churned')], default='not_invited', max_length=24)),
                ('persona', models.CharField(choices=[('international_student', 'International student'), ('visa_holder', 'Visa holder'), ('scholarship_applicant', 'Scholarship applicant'), ('freelancer', 'Freelancer'), ('family_user', 'Family user'), ('student_leader', 'Student leader'), ('traveler', 'Traveler'), ('other', 'Other')], default='other', max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beta_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
                'indexes': [models.Index(fields=['invite_status', 'persona'], name='founder_bet_invite__a3d9af_idx')],
            },
        ),
        migrations.CreateModel(
            name='FounderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='founder_fou_action_a359a1_idx'), models.Index(fields=['actor', 'created_at'], name='founder_fou_actor_i_567685_idx')],
            },
        ),
    ]
