# Generated by Django 5.2.15 on 2026-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0002_featurecompletionitem_launchchecklistitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('user_signed_up', 'User signed up'), ('user_logged_in', 'User logged in'), ('onboarding_started', 'Onboarding started'), ('onboarding_completed', 'Onboarding completed'), ('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_trashed', 'Document trashed'), ('document_restored', 'Document restored'), ('file_uploaded', 'File uploaded'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('expiry_date_added', 'Expiry date added'), ('reminder_created', 'Reminder created'), ('attention_needed_viewed', 'Attention needed viewed'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('bundle_created', 'Bundle created'), ('share_link_created', 'Share link created'), ('share_link_opened', 'Share link opened'), ('share_link_revoked', 'Share link revoked'), ('access_code_failed', 'Access code failed'), ('access_code_verified', 'Access code verified'), ('export_requested', 'Export requested'), ('export_created', 'Export created'), ('bundle_exported', 'Bundle exported'), ('emergency_pack_created', 'Emergency pack created'), ('proof_created', 'Proof created'), ('proof_record_created', 'Proof record created'), ('account_deletion_requested', 'Account deletion requested'), ('feedback_submitted', 'Feedback submitted'), ('error_recorded', 'Error recorded'), ('security_event_recorded', 'Security event recorded'), ('timeline_viewed', 'Timeline viewed'), ('trash_restore_used', 'Trash restore used'), ('extraction_requested', 'Extraction requested')], max_length=64),
        ),
    ]
