# Generated by Django 5.2.15 on 2026-06-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0003_alter_productevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('user_signed_up', 'User signed up'), ('user_logged_in', 'User logged in'), ('onboarding_started', 'Onboarding started'), ('onboarding_completed', 'Onboarding completed'), ('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_trashed', 'Document trashed'), ('document_restored', 'Document restored'), ('file_uploaded', 'File uploaded'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('expiry_date_added', 'Expiry date added'), ('reminder_created', 'Reminder created'), ('attention_needed_viewed', 'Attention needed viewed'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('bundle_created', 'Bundle created'), ('share_link_created', 'Share link created'), ('share_link_opened', 'Share link opened'), ('share_link_revoked', 'Share link revoked'), ('access_code_failed', 'Access code failed'), ('access_code_verified', 'Access code verified'), ('export_requested', 'Export requested'), ('export_created', 'Export created'), ('bundle_exported', 'Bundle exported'), ('emergency_pack_created', 'Emergency pack created'), ('proof_created', 'Proof created'), ('proof_record_created', 'Proof record created'), ('account_deletion_requested', 'Account deletion requested'), ('feedback_submitted', 'Feedback submitted'), ('error_recorded', 'Error recorded'), ('security_event_recorded', 'Security event recorded'), ('timeline_viewed', 'Timeline viewed'), ('trash_restore_used', 'Trash restore used'), ('extraction_requested', 'Extraction requested'), ('waitlist_joined', 'Waitlist joined'), ('invite_created', 'Invite created'), ('invite_sent_or_copied', 'Invite sent or copied'), ('invite_validated', 'Invite validated'), ('invite_used', 'Invite used'), ('private_beta_signup_completed', 'Private beta signup completed')], max_length=64),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=140)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('persona_target', models.CharField(blank=True, choices=[('international_student', 'International student'), ('visa_holder', 'Visa holder'), ('scholarship_applicant', 'Scholarship applicant'), ('freelancer', 'Freelancer'), ('family_documents', 'Family documents'), ('traveler', 'Traveler'), ('student_leader', 'Student leader'), ('other', 'Other')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('persona', models.CharField(choices=[('international_student', 'International student'), ('visa_holder', 'Visa holder'), ('scholarship_applicant', 'Scholarship applicant'), ('freelancer', 'Freelancer'), ('family_documents', 'Family documents'), ('traveler', 'Traveler'), ('student_leader', 'Student leader'), ('other', 'Other')], max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('founder_notes', models.TextField(blank=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='founder.invitecode')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteCodeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='founder.invitecode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_code_uses', to=settings.AUTH_USER_MODEL)),
                ('waitlist_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_uses', to='founder.waitlistentry')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='founder_inv_code_2cbfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['is_active', 'expires_at'], name='founder_inv_is_acti_facfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['persona_target', 'created_at'], name='founder_inv_persona_d6b4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['email', 'status'], name='founder_wai_email_9d4683_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['status', 'created_at'], name='founder_wai_status_c88d41_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['persona', 'created_at'], name='founder_wai_persona_62059a_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['country', 'created_at'], name='founder_wai_country_0e6c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecodeuse',
            index=models.Index(fields=['email', 'used_at'], name='founder_inv_email_922aff_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecodeuse',
            index=models.Index(fields=['invite_code', 'used_at'], name='founder_inv_invite__cfd54c_idx'),
        ),
    ]
