# Generated by Django 5.2.15 on 2026-06-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0007_alter_productevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('content', models.CharField(blank=True, max_length=120)),
                ('target_audience', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('cta', models.CharField(blank=True, max_length=160)),
                ('landing_url', models.URLField(blank=True)),
                ('generated_url', models.URLField(blank=True, max_length=600)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_campaigns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('action_type', models.CharField(blank=True, max_length=60)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('related_metric', models.CharField(blank=True, max_length=120)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_automatically', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_actions_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_actions_owned', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_actions', to='founder.marketingcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=160)),
                ('base_url', models.URLField(max_length=600)),
                ('full_url', models.URLField(max_length=600)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('content', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_campaign_links', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='founder.marketingcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['status', 'created_at'], name='founder_mar_status_f435b0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['campaign'], name='founder_mar_campaig_e0a1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='growthaction',
            index=models.Index(fields=['status', 'priority'], name='founder_gro_status_307bbc_idx'),
        ),
    ]
