# Generated by Django 5.2.15 on 2026-06-15 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0008_marketingcampaign_growthaction_campaignlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('community', models.CharField(blank=True, max_length=160)),
                ('campus', models.CharField(blank=True, max_length=160)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('invited', 'Invited'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('removed', 'Removed')], default='candidate', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('reward_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_ambassadors_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('rules_json', models.JSONField(blank=True, default=dict)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('reward_status', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('target_audience', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('measuring', 'Measuring'), ('repurpose', 'Repurpose'), ('archived', 'Archived')], default='idea', max_length=16)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cta', models.CharField(blank=True, max_length=160)),
                ('utm_link', models.URLField(blank=True, max_length=600)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('result_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='founder.marketingcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_content_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='founder_con_status_8776dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('signed_up', 'Signed up'), ('activated', 'Activated'), ('converted', 'Converted')], default='signed_up', max_length=16)),
                ('reward_status', models.CharField(blank=True, max_length=40)),
                ('signup_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_attributions', to='founder.marketingcampaign')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signup_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='founder_ref_referre_a92397_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_utm_source', models.CharField(blank=True, max_length=120)),
                ('first_utm_medium', models.CharField(blank=True, max_length=120)),
                ('first_utm_campaign', models.CharField(blank=True, max_length=120)),
                ('first_utm_content', models.CharField(blank=True, max_length=120)),
                ('first_utm_term', models.CharField(blank=True, max_length=120)),
                ('first_referrer', models.CharField(blank=True, max_length=300)),
                ('first_landing_page', models.CharField(blank=True, max_length=300)),
                ('last_utm_source', models.CharField(blank=True, max_length=120)),
                ('last_utm_medium', models.CharField(blank=True, max_length=120)),
                ('last_utm_campaign', models.CharField(blank=True, max_length=120)),
                ('last_utm_content', models.CharField(blank=True, max_length=120)),
                ('last_utm_term', models.CharField(blank=True, max_length=120)),
                ('last_referrer', models.CharField(blank=True, max_length=300)),
                ('last_landing_page', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['first_utm_campaign'], name='founder_use_first_u_26c219_idx')],
            },
        ),
    ]
