# Generated by Django 5.2.15 on 2026-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0009_ambassadorprofile_audiencesegment_referralprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_documents', models.PositiveIntegerField(default=0)),
                ('event_counts', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='founder_dai_date_5046e5_idx')],
            },
        ),
    ]
