# Generated by Django 5.2.15 on 2026-06-25 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0011_transactionalemailsetting'),
        ('organizations', '0010_organizationcasetemplate_default_custom_field_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('upload', 'Upload'), ('storage', 'Storage'), ('email', 'Email'), ('ai', 'AI'), ('scheduled_job', 'Scheduled job'), ('public_link', 'Public link'), ('billing', 'Billing'), ('security', 'Security'), ('portal', 'Portal'), ('scanner', 'Scanner'), ('pwa', 'PWA')], max_length=24)),
                ('source', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('degraded', 'Degraded')], default='failed', max_length=16)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_operational_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='founder_ope_categor_6f93d4_idx'), models.Index(fields=['severity', 'created_at'], name='founder_ope_severit_3ac7c3_idx'), models.Index(fields=['status', 'created_at'], name='founder_ope_status_47aaaa_idx'), models.Index(fields=['resolved', 'severity', 'created_at'], name='founder_ope_resolve_edf677_idx'), models.Index(fields=['source', 'created_at'], name='founder_ope_source_ce9df7_idx')],
            },
        ),
    ]
