# Generated by Django 5.2.15 on 2026-06-25 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0012_operationalevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('stale', 'Stale'), ('cancelled', 'Cancelled')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('manual', 'Manual'), ('command', 'Command'), ('system', 'System')], default='scheduler', max_length=16)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('lock_key', models.CharField(blank=True, max_length=120)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('safe_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operational_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_job_runs', to='founder.operationalevent')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scheduled_job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_name', 'created_at'], name='founder_sch_job_nam_233461_idx'), models.Index(fields=['status', 'created_at'], name='founder_sch_status_b19e8d_idx'), models.Index(fields=['job_name', 'status', 'created_at'], name='founder_sch_job_nam_00fc5b_idx')],
            },
        ),
    ]
