# Generated by Django 5.2.15 on 2026-06-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0013_scheduledjobrun'),
        ('organizations', '0010_organizationcasetemplate_default_custom_field_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderSupportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('support', 'Support'), ('beta', 'Beta'), ('billing', 'Billing'), ('technical', 'Technical'), ('risk', 'Risk')], default='support', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('watching', 'Watching'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_support_notes', to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_notes', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='founder_fou_target__ef45cd_idx'), models.Index(fields=['target_organization', 'created_at'], name='founder_fou_target__8d1803_idx'), models.Index(fields=['status', 'created_at'], name='founder_fou_status_bd8760_idx')],
            },
        ),
    ]
