# Generated by Django 5.2.15 on 2026-06-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_organizationcasetemplate_default_custom_field_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedIntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('dropbox', 'Dropbox'), ('other', 'Other')], max_length=20)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('scope_groups', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('access_token_ciphertext', models.BinaryField(blank=True, null=True)),
                ('refresh_token_ciphertext', models.BinaryField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='integration_user_id_43af5e_idx'), models.Index(fields=['status'], name='integration_status_43a697_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'provider_account_id'), name='uniq_user_provider_account')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('dropbox', 'Dropbox'), ('other', 'Other')], max_length=20)),
                ('state_hash', models.CharField(db_index=True, max_length=64)),
                ('redirect_path', models.CharField(blank=True, max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('scope_groups', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state_hash', 'provider'], name='integration_state_h_2fecd4_idx')],
            },
        ),
    ]
