# Generated by Django 5.2.15 on 2026-06-25 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_documentcollection_documentcollectionitem_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedGmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id_hash', models.CharField(db_index=True, max_length=64)),
                ('provider_attachment_id_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('imported', 'Imported')], default='imported', max_length=20)),
                ('sanitized_metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_gmail_attachments', to='integrations.connectedintegrationaccount')),
                ('imported_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('imported_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_gmail_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['user', 'account'], name='integration_user_id_9c8e20_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'account', 'provider_message_id_hash', 'provider_attachment_id_hash'), name='uniq_user_account_gmail_attachment')],
            },
        ),
    ]
