# Generated by Django 5.2.15 on 2026-06-25 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_documentcollection_documentcollectionitem_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('dropbox', 'Dropbox'), ('other', 'Other')], default='google', max_length=20)),
                ('provider_calendar_id', models.CharField(max_length=255)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('sanitized_title', models.CharField(blank=True, max_length=255)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('removed', 'Removed')], default='imported', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_calendar_events', to='integrations.connectedintegrationaccount')),
                ('imported_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('imported_reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentreminderrule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['owner', 'provider'], name='integration_owner_i_754fe4_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider', 'provider_calendar_id', 'provider_event_id'), name='uniq_imported_calendar_event_per_owner')],
            },
        ),
    ]
