# Generated by Django 5.2.15 on 2026-06-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_importedcalendarevent'),
        ('integrations', '0002_importedgmailattachment'),
    ]

    operations = [
    ]
