# Generated by Django 5.2.15 on 2026-06-12 23:38

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFileShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('permission', models.CharField(choices=[('view_only', 'View only'), ('download_allowed', 'View and download')], default='view_only', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_required', models.BooleanField(default=False)),
                ('access_code_hash', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_share_links', to='documents.document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_file_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('file_uploaded', 'File uploaded'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('share_created', 'Share link created'), ('share_opened', 'Share link opened'), ('share_previewed', 'Shared file previewed'), ('share_downloaded', 'Shared file downloaded'), ('share_revoked', 'Share link revoked'), ('share_access_code_verified', 'Access code verified'), ('share_access_code_failed', 'Access code failed'), ('file_deleted', 'File deleted')], max_length=64)),
                ('actor_type', models.CharField(choices=[('owner', 'Owner'), ('shared_viewer', 'Shared viewer'), ('system', 'System')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_activities', to='documents.document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_file_activities', to=settings.AUTH_USER_MODEL)),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='documents.documentfilesharelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentfilesharelink',
            index=models.Index(fields=['file', 'created_at'], name='documents_d_file_id_7da708_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfileactivity',
            index=models.Index(fields=['file', 'created_at'], name='documents_d_file_id_be7ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfileactivity',
            index=models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_887998_idx'),
        ),
    ]
