# Generated by Django 5.2.15 on 2026-06-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentfilesharelink_documentfileactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('before_expiry', 'Before expiry'), ('before_renewal_date', 'Before renewal date'), ('on_expiry', 'On expiry')], default='before_expiry', max_length=32)),
                ('days_before', models.PositiveIntegerField(default=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reminder_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['days_before', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_enabled'], name='documents_d_owner_i_37a613_idx'), models.Index(fields=['document', 'trigger_type'], name='documents_d_documen_2949cb_idx')],
            },
        ),
    ]
