# Generated by Django 5.2.15 on 2026-06-13 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentreminderrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bundle_type', models.CharField(choices=[('renewal', 'Renewal'), ('application', 'Application'), ('travel', 'Travel'), ('emergency', 'Emergency'), ('scholarship', 'Scholarship'), ('insurance', 'Insurance'), ('custom', 'Custom')], default='renewal', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('authority_or_provider', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('readiness_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBundleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('requirement_type', models.CharField(choices=[('document', 'Document'), ('file', 'File'), ('proof', 'Proof'), ('payment', 'Payment'), ('form', 'Form'), ('other', 'Other')], default='document', max_length=20)),
                ('expected_document_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('attached', 'Attached'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='missing', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='documents.documentbundle')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_requirements', to='documents.document')),
                ('linked_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_requirements', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bundle_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('checklist_type', models.CharField(choices=[('renewal', 'Renewal'), ('application', 'Application'), ('travel', 'Travel'), ('insurance', 'Insurance'), ('custom', 'Custom')], default='renewal', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='documents.documentbundle')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentchecklist')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='documents.document')),
                ('linked_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('use_case', models.CharField(blank=True, max_length=100)),
                ('checklist_type', models.CharField(choices=[('renewal', 'Renewal'), ('application', 'Application'), ('travel', 'Travel'), ('insurance', 'Insurance'), ('custom', 'Custom')], default='renewal', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_system_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='documents_d_is_acti_a56a51_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('suggested_due_offset_days', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to='documents.documentchecklisttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documentchecklist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='documents.documentchecklisttemplate'),
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('local_text', 'Local text'), ('future_ocr', 'Future OCR')], default='local_text', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.document')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentbundle',
            index=models.Index(fields=['owner', 'status'], name='documents_d_owner_i_a1e582_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbundle',
            index=models.Index(fields=['owner', 'target_date'], name='documents_d_owner_i_f7fb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbundlerequirement',
            index=models.Index(fields=['bundle', 'sort_order'], name='documents_d_bundle__eb8328_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbundlerequirement',
            index=models.Index(fields=['owner', 'status'], name='documents_d_owner_i_fda3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchecklistitem',
            index=models.Index(fields=['checklist', 'sort_order'], name='documents_d_checkli_872a16_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchecklist',
            index=models.Index(fields=['owner', 'status'], name='documents_d_owner_i_6769d7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchecklist',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_504e42_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextraction',
            index=models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_836d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextraction',
            index=models.Index(fields=['file', 'created_at'], name='documents_d_file_id_72e226_idx'),
        ),
    ]
