# Generated by Django 5.2.15 on 2026-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentbundle_documentbundlerequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentextraction',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('local_text', 'Local text'), ('local_ocr', 'Local OCR (Tesseract)'), ('future_ocr', 'Future OCR')], default='local_text', max_length=20),
        ),
    ]
