# Generated by Django 5.2.15 on 2026-06-13 05:14

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentextraction_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_trashed', 'Document moved to trash'), ('document_restored', 'Document restored'), ('document_version_restored', 'Version restored'), ('file_trashed', 'File moved to trash'), ('file_restored', 'File restored'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('extraction_requested', 'Detail extraction requested'), ('extraction_applied', 'Extracted details applied'), ('proof_saved', 'Proof saved'), ('export_requested', 'Export requested'), ('emergency_pack_created', 'Emergency pack created'), ('emergency_pack_opened', 'Emergency pack opened')], max_length=48)),
                ('actor_type', models.CharField(default='owner', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('documents_json', 'Documents (JSON)'), ('documents_csv', 'Documents (CSV)'), ('full_vault_metadata', 'Full vault metadata (JSON)'), ('future_full_archive', 'Full archive (future)')], default='documents_json', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.export_upload_to)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('version_type', models.CharField(choices=[('file_upload', 'File uploaded'), ('file_replacement', 'File replaced'), ('metadata_snapshot', 'Metadata snapshot'), ('extraction_applied', 'Extraction applied'), ('manual_update', 'Manual update')], default='metadata_snapshot', max_length=32)),
                ('title_snapshot', models.CharField(blank=True, max_length=255)),
                ('document_type_snapshot', models.CharField(blank=True, max_length=100)),
                ('issuer_snapshot', models.CharField(blank=True, max_length=255)),
                ('country_snapshot', models.CharField(blank=True, max_length=100)),
                ('reference_number_snapshot', models.CharField(blank=True, max_length=255)),
                ('issue_date_snapshot', models.DateField(blank=True, null=True)),
                ('expiry_date_snapshot', models.DateField(blank=True, null=True)),
                ('renewal_date_snapshot', models.DateField(blank=True, null=True)),
                ('notes_snapshot', models.TextField(blank=True)),
                ('file_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('file_size_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('file_content_type_snapshot', models.CharField(blank=True, max_length=120)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccessPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('access_mode', models.CharField(choices=[('owner_only_preview', 'Owner only (preview)'), ('share_link', 'Shareable link'), ('future_trusted_contact', 'Trusted contact (future)')], default='owner_only_preview', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_required', models.BooleanField(default=False)),
                ('access_code_hash', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccessPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('proof_type', models.CharField(choices=[('submission_confirmation', 'Submission confirmation'), ('payment_receipt', 'Payment receipt'), ('tracking_number', 'Tracking number'), ('approval_letter', 'Approval letter'), ('rejection_notice', 'Rejection notice'), ('email_confirmation', 'Email confirmation'), ('other', 'Other')], default='submission_confirmation', max_length=32)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('submitted_to', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_follow_up', 'Needs follow-up'), ('archived', 'Archived')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='certified_copy_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_about_original',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='physical_location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='physical_location_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_trashed'], name='documents_d_owner_i_cae4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['document', 'is_trashed'], name='documents_d_documen_b2fb65_idx'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='related_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentbundle'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='related_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentchecklist'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='related_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='documentexportrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccesspackitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_pack_items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='emergencyaccesspackitem',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_pack_items', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='emergencyaccesspackitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_pack_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccesspackitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.emergencyaccesspack'),
        ),
        migrations.AddField(
            model_name='proofrecord',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_records', to='documents.documentbundle'),
        ),
        migrations.AddField(
            model_name='proofrecord',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_records', to='documents.documentchecklist'),
        ),
        migrations.AddField(
            model_name='proofrecord',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_records', to='documents.document'),
        ),
        migrations.AddField(
            model_name='proofrecord',
            name='linked_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_records', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='proofrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='related_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.proofrecord'),
        ),
        migrations.AddIndex(
            model_name='documentexportrequest',
            index=models.Index(fields=['owner', 'requested_at'], name='documents_d_owner_i_9f45e5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_621e30_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='documents_d_documen_68fe34_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number'),
        ),
        migrations.AddIndex(
            model_name='emergencyaccesspack',
            index=models.Index(fields=['owner', 'status'], name='documents_e_owner_i_d19895_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyaccesspackitem',
            index=models.Index(fields=['pack', 'sort_order'], name='documents_e_pack_id_b6886a_idx'),
        ),
        migrations.AddIndex(
            model_name='proofrecord',
            index=models.Index(fields=['owner', 'created_at'], name='documents_p_owner_i_f3e882_idx'),
        ),
        migrations.AddIndex(
            model_name='proofrecord',
            index=models.Index(fields=['document', 'created_at'], name='documents_p_documen_a00661_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_0a3aed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_fb9c15_idx'),
        ),
    ]
