# Generated by Django 5.2.15 on 2026-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentactivity_documentexportrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentexportrequest',
            name='export_type',
            field=models.CharField(choices=[('documents_json', 'Documents (JSON)'), ('documents_csv', 'Documents (CSV)'), ('full_vault_metadata', 'Full vault metadata (JSON)'), ('bundle_metadata_json', 'Bundle metadata (JSON)'), ('bundle_requirements_csv', 'Bundle requirements (CSV)'), ('future_full_archive', 'Full archive (future)')], default='documents_json', max_length=32),
        ),
    ]
