# Generated by Django 5.2.15 on 2026-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfilesharelink',
            name='access_limit_type',
            field=models.CharField(choices=[('unlimited', 'Unlimited access'), ('one_time', 'One-time view'), ('limited_count', 'Limited number of views')], default='unlimited', max_length=20),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='limit_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='max_downloads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='max_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentfileactivity',
            name='action',
            field=models.CharField(choices=[('file_uploaded', 'File uploaded'), ('file_previewed', 'File previewed'), ('file_downloaded', 'File downloaded'), ('share_created', 'Share link created'), ('share_opened', 'Share link opened'), ('share_previewed', 'Shared file previewed'), ('share_downloaded', 'Shared file downloaded'), ('share_revoked', 'Share link revoked'), ('share_access_code_verified', 'Access code verified'), ('share_access_code_failed', 'Access code failed'), ('share_limit_reached', 'Share access limit reached'), ('share_blocked_limit_reached', 'Share access blocked (limit reached)'), ('file_deleted', 'File deleted')], max_length=64),
        ),
    ]
