# Generated by Django 5.2.15 on 2026-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentfilesharelink_access_limit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfilesharelink',
            name='privacy_screen_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfilesharelink',
            name='watermark_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
