# Generated by Django 5.2.15 on 2026-06-13 15:10

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentfilesharelink_privacy_screen_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('permission', models.CharField(choices=[('view_only', 'View only'), ('download_allowed', 'View and download')], default='view_only', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_required', models.BooleanField(default=False)),
                ('access_code_hash', models.CharField(blank=True, max_length=255)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('privacy_screen_enabled', models.BooleanField(default=False)),
                ('access_limit_type', models.CharField(choices=[('unlimited', 'Unlimited access'), ('one_time', 'One-time view'), ('limited_count', 'Limited number of views')], default='unlimited', max_length=20)),
                ('max_views', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('limit_reached_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('room_created', 'Room created'), ('room_opened', 'Room opened'), ('room_previewed', 'Room item previewed'), ('room_downloaded', 'Room item downloaded'), ('room_revoked', 'Room revoked'), ('room_access_code_verified', 'Access code verified'), ('room_access_code_failed', 'Access code failed'), ('room_limit_reached', 'Room access limit reached'), ('room_blocked_limit_reached', 'Room access blocked (limit reached)')], max_length=64)),
                ('actor_type', models.CharField(choices=[('owner', 'Owner'), ('shared_viewer', 'Shared viewer'), ('system', 'System')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_activities', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.shareroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareRoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_room_items', to='documents.document')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_room_items', to='documents.documentfile')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_room_items', to='documents.proofrecord')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.shareroom')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shareroom',
            index=models.Index(fields=['owner', 'created_at'], name='documents_s_owner_i_6aad7a_idx'),
        ),
        migrations.AddIndex(
            model_name='shareroom',
            index=models.Index(fields=['token'], name='documents_s_token_868054_idx'),
        ),
        migrations.AddIndex(
            model_name='shareroom',
            index=models.Index(fields=['owner', 'revoked_at'], name='documents_s_owner_i_400229_idx'),
        ),
        migrations.AddIndex(
            model_name='shareroom',
            index=models.Index(fields=['expires_at'], name='documents_s_expires_1d256d_idx'),
        ),
        migrations.AddIndex(
            model_name='roomactivity',
            index=models.Index(fields=['room', 'created_at'], name='documents_r_room_id_6cac15_idx'),
        ),
        migrations.AddIndex(
            model_name='roomactivity',
            index=models.Index(fields=['owner', 'created_at'], name='documents_r_owner_i_48d862_idx'),
        ),
        migrations.AddIndex(
            model_name='shareroomitem',
            index=models.Index(fields=['room', 'sort_order'], name='documents_s_room_id_8cd83f_idx'),
        ),
    ]
