# Generated by Django 5.2.15 on 2026-06-14 08:49

import uuid
from django.db import migrations, models


def backfill_file_uuids(apps, schema_editor):
    """Assign a distinct UUID to every existing row before the unique
    constraint is applied (a callable default would otherwise reuse one
    value across all rows)."""
    DocumentFile = apps.get_model("documents", "DocumentFile")
    for pk in DocumentFile.objects.values_list("pk", flat=True).iterator():
        DocumentFile.objects.filter(pk=pk).update(file_uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_file_inbox_unassigned_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='ciphertext_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='ciphertext_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='encrypted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='encryption_algorithm',
            field=models.CharField(default='AES-256-GCM', max_length=64),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='encryption_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='encryption_status',
            field=models.CharField(choices=[('plaintext_legacy', 'Plaintext legacy'), ('encrypting', 'Encrypting'), ('encrypted', 'Encrypted'), ('encryption_failed', 'Encryption failed')], db_index=True, default='plaintext_legacy', max_length=32),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='encryption_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        # Add nullable + non-unique first, backfill distinct values, then make
        # it unique — safe for tables that already contain rows.
        migrations.AddField(
            model_name='documentfile',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_file_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentfile',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='gcm_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='kek_version',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='plaintext_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='wrapped_dek',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
