# Generated by Django 5.2.15 on 2026-06-14 09:10

from django.db import migrations, models


def encrypt_existing_notes(apps, schema_editor):
    """Encrypt any pre-existing plaintext ProofRecord.notes into
    notes_ciphertext, then blank the plaintext column. Best-effort: if no
    encryption key is configured (KeyConfigurationError), leave the plaintext
    in place — it stays readable via the legacy fallback and can be migrated
    later once keys are configured."""
    from apps.core.security import encryption, key_provider

    try:
        key_provider.get_active_kek()
    except key_provider.KeyConfigurationError:
        return

    ProofRecord = apps.get_model("documents", "ProofRecord")
    for proof in ProofRecord.objects.exclude(notes="").iterator():
        if proof.notes_ciphertext:
            continue
        token = encryption.encrypt_field_value(
            proof.notes, model="proofrecord", field="notes", record_id=proof.pk
        )
        ProofRecord.objects.filter(pk=proof.pk).update(
            notes_ciphertext=token, notes=""
        )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documentfile_ciphertext_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofrecord',
            name='notes_ciphertext',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_notes, migrations.RunPython.noop),
    ]
