# Generated by Django 5.2.15 on 2026-06-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_proofrecord_notes_ciphertext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='uniq_system_document_category_name'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_document_category_name'),
        ),
    ]
