# Generated by Django 5.2.15 on 2026-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_documentcategory_owner_alter_documentcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
