# Generated by Django 5.2.15 on 2026-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_documentcategory_color_documentcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
