# Generated by Django 5.2.15 on 2026-06-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='access_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='allow_downloads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='last_known_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='last_known_location_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='location_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='location_precision',
            field=models.CharField(choices=[('approximate', 'Approximate'), ('precise', 'Precise')], default='approximate', max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='unlock_delay_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='unlock_mode',
            field=models.CharField(choices=[('owner_approval', 'Owner approval only'), ('delayed', 'Delayed unlock'), ('instant_code', 'Instant with code'), ('disabled_until_activated', 'Disabled until activated')], default='instant_code', max_length=32),
        ),
        migrations.CreateModel(
            name='EmergencyActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('setup_created', 'Setup created'), ('documents_changed', 'Emergency documents changed'), ('contact_added', 'Trusted contact added'), ('contact_removed', 'Trusted contact removed'), ('contact_notified', 'Trusted contact notified'), ('qr_generated', 'QR generated'), ('qr_regenerated', 'QR regenerated'), ('qr_scanned', 'QR scanned / link opened'), ('request_submitted', 'Request submitted'), ('wrong_code', 'Wrong code attempt'), ('countdown_started', 'Delayed countdown started'), ('access_approved', 'Access approved'), ('access_denied', 'Access denied'), ('access_unlocked', 'Access unlocked'), ('document_viewed', 'Document viewed'), ('document_downloaded', 'Document downloaded'), ('location_requested', 'Location requested'), ('location_revealed', 'Location revealed'), ('location_updated', 'Location updated'), ('location_toggled', 'Location sharing toggled'), ('access_revoked', 'Access revoked'), ('unlock_mode_changed', 'Unlock mode changed'), ('setup_disabled', 'Setup disabled'), ('setup_enabled', 'Setup enabled')], max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_activity_events', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='documents.emergencyaccesspack')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pack', '-created_at'], name='documents_e_pack_id_709e34_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTrustedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('friend', 'Friend'), ('guardian', 'Guardian'), ('roommate', 'Roommate'), ('colleague', 'Colleague'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_backup', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('can_request', 'Can request access'), ('instant_with_code', 'Can access instantly with QR + code'), ('notify_only', 'Can only be notified')], default='can_request', max_length=24)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('notified', 'Setup notice sent'), ('verified', 'Verified')], default='unverified', max_length=16)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_trusted_contacts', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to='documents.emergencyaccesspack')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['pack', 'is_primary'], name='documents_e_pack_id_5c54bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('requester_name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending owner approval'), ('countdown', 'Delayed unlock counting down'), ('unlocked', 'Unlocked'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='documents.emergencyaccesspack')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pack', 'status'], name='documents_e_pack_id_dbaf32_idx')],
            },
        ),
    ]
