# Generated by Django 5.2.15 on 2026-06-16 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_emergencyaccesspack_access_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_trashed', '-is_pinned', '-created_at'], name='doc_owner_active_listing'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_trashed', 'status'], name='doc_owner_trashed_status'),
        ),
    ]
