# Generated by Django 5.2.15 on 2026-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_doc_owner_active_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attention_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
