# Generated by Django 5.2.15 on 2026-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_doc_owner_active_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_trashed', 'Document moved to trash'), ('document_restored', 'Document restored'), ('document_version_restored', 'Version restored'), ('file_trashed', 'File moved to trash'), ('file_restored', 'File restored'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('extraction_requested', 'Detail extraction requested'), ('extraction_applied', 'Extracted details applied'), ('proof_saved', 'Proof saved'), ('export_requested', 'Export requested'), ('emergency_pack_created', 'Emergency pack created'), ('emergency_pack_opened', 'Emergency pack opened'), ('reminder_added', 'Reminder added'), ('added_to_bundle', 'Added to a bundle')], max_length=48),
        ),
    ]
