# Generated by Django 5.2.15 on 2026-06-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_attention_snoozed_until'),
        ('documents', '0022_alter_documentactivity_action'),
    ]

    operations = [
    ]
