# Generated by Django 5.2.15 on 2026-06-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_merge_20260618_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentextraction',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.document'),
        ),
    ]
