# Generated by Django 5.2.15 on 2026-06-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_alter_documentextraction_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_trashed', 'Document moved to trash'), ('document_restored', 'Document restored'), ('document_version_restored', 'Version restored'), ('file_trashed', 'File moved to trash'), ('file_restored', 'File restored'), ('checklist_created', 'Checklist created'), ('checklist_item_completed', 'Checklist item completed'), ('extraction_requested', 'Detail extraction requested'), ('extraction_applied', 'Extracted details applied'), ('proof_saved', 'Proof saved'), ('export_requested', 'Export requested'), ('emergency_pack_created', 'Emergency pack created'), ('emergency_pack_opened', 'Emergency pack opened'), ('reminder_added', 'Reminder added'), ('added_to_bundle', 'Added to a bundle'), ('shared_via_safesend', 'Shared via SafeSend'), ('bundle_created', 'Pack created'), ('bundle_template_applied', 'Template applied'), ('bundle_requirement_added', 'Checklist item added'), ('bundle_requirement_removed', 'Checklist item removed'), ('bundle_requirement_status_changed', 'Checklist item updated'), ('bundle_status_changed', 'Pack status changed'), ('bundle_exported', 'Pack exported')], max_length=48),
        ),
    ]
