# Generated by Django 5.2.15 on 2026-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_documentactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_armed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_nudge_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_reveal_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyaccesspack',
            name='checkin_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyactivityevent',
            name='event_type',
            field=models.CharField(choices=[('setup_created', 'Setup created'), ('documents_changed', 'Emergency documents changed'), ('contact_added', 'Trusted contact added'), ('contact_removed', 'Trusted contact removed'), ('contact_notified', 'Trusted contact notified'), ('qr_generated', 'QR generated'), ('qr_regenerated', 'QR regenerated'), ('qr_scanned', 'QR scanned / link opened'), ('request_submitted', 'Request submitted'), ('wrong_code', 'Wrong code attempt'), ('countdown_started', 'Delayed countdown started'), ('access_approved', 'Access approved'), ('access_denied', 'Access denied'), ('access_unlocked', 'Access unlocked'), ('document_viewed', 'Document viewed'), ('document_downloaded', 'Document downloaded'), ('location_requested', 'Location requested'), ('location_revealed', 'Location revealed'), ('location_updated', 'Location updated'), ('location_toggled', 'Location sharing toggled'), ('access_revoked', 'Access revoked'), ('unlock_mode_changed', 'Unlock mode changed'), ('setup_disabled', 'Setup disabled'), ('setup_enabled', 'Setup enabled'), ('checkin_armed', 'Safety check-in armed'), ('checkin_extended', 'Safety check-in extended'), ('checkin_canceled', 'Safety check-in canceled'), ('checkin_triggered', 'Safety check-in escalation fired')], max_length=32),
        ),
    ]
