# Generated by Django 5.2.15 on 2026-06-21 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_documentembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_type', models.CharField(choices=[('fill_sign', 'Fill & Sign')], default='fill_sign', max_length=32)),
                ('annotations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_documents', to='documents.document')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_as_original', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_documents', to=settings.AUTH_USER_MODEL)),
                ('prepared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_as_copy', to='documents.documentfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('signature_method', models.CharField(choices=[('drawn', 'Drawn'), ('typed', 'Typed'), ('uploaded', 'Uploaded'), ('none', 'Fill only (no signature)')], default='none', max_length=16)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_file_hash', models.CharField(blank=True, max_length=64)),
                ('prepared_file_hash', models.CharField(blank=True, max_length=64)),
                ('audit_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_records', to=settings.AUTH_USER_MODEL)),
                ('prepared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_records', to='documents.prepareddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prepareddocument',
            index=models.Index(fields=['owner', '-created_at'], name='documents_p_owner_i_7c3f45_idx'),
        ),
        migrations.AddIndex(
            model_name='prepareddocument',
            index=models.Index(fields=['document'], name='documents_p_documen_6f7204_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignaturerecord',
            index=models.Index(fields=['owner', '-created_at'], name='documents_d_owner_i_96baae_idx'),
        ),
    ]
