# Generated by Django 5.2.15 on 2026-06-21 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_prepareddocument_documentsignaturerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('cv', 'CV / résumé'), ('cover_letter', 'Cover letter'), ('motivation_letter', 'Motivation letter'), ('statement_of_purpose', 'Statement of purpose'), ('recommendation_email', 'Recommendation request email'), ('formal_letter', 'Formal request letter'), ('application_email', 'Application email'), ('request_message', 'Document request message'), ('pack_cover_sheet', 'Pack cover sheet'), ('other', 'Other')], default='other', max_length=32)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('discarded', 'Discarded')], default='draft', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('related_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.documentbundle')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='documents_g_owner_i_e2f96c_idx'), models.Index(fields=['related_pack'], name='documents_g_related_c0da4b_idx')],
            },
        ),
    ]
