# Generated by Django 5.2.15 on 2026-06-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_generateddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(blank=True, max_length=64)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_label', models.CharField(blank=True, max_length=120)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=64)),
                ('embedding_created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('embedding_failed', 'Embedding failed'), ('skipped', 'Skipped')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['owner', 'document'], name='documents_d_owner_i_1cd78b_idx'), models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_2bd090_idx'), models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx'), models.Index(fields=['text_hash'], name='documents_d_text_ha_dd6e37_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_document_chunk_index')],
            },
        ),
    ]
