# Generated by Django 5.2.15 on 2026-06-24 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_documentchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementExtractionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('created_requirements', models.PositiveIntegerField(default=0)),
                ('created_reminders', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_extraction_drafts', to='documents.documentbundle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_extraction_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'bundle'], name='documents_r_owner_i_563a9a_idx'), models.Index(fields=['bundle', 'status'], name='documents_r_bundle__a683cd_idx')],
            },
        ),
    ]
