# Generated by Django 5.2.15 on 2026-06-24 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_requirementextractiondraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('university', 'University'), ('visa', 'Visa'), ('job', 'Job'), ('internship', 'Internship'), ('grant', 'Grant'), ('permit', 'Permit'), ('renewal', 'Renewal'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('checklist_created', 'Checklist created'), ('documents_missing', 'Documents missing'), ('ready_to_submit', 'Ready to submit'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('renewal_needed', 'Renewal needed')], default='planning', max_length=24)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_applications', to='documents.documentbundle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_archived', '-updated_at'], name='documents_t_owner_i_fd16f6_idx'), models.Index(fields=['owner', 'status'], name='documents_t_owner_i_d9161d_idx'), models.Index(fields=['owner', 'deadline_date'], name='documents_t_owner_i_f711e7_idx')],
            },
        ),
    ]
