# Generated by Django 5.2.15 on 2026-06-24 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_trackedapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ats_resume', 'ATS resume'), ('academic_cv', 'Academic CV'), ('scholarship_cv', 'Scholarship CV'), ('cover_letter', 'Cover letter'), ('motivation_letter', 'Motivation letter'), ('statement_of_purpose', 'Statement of purpose'), ('recommendation_request_email', 'Recommendation request email'), ('application_email', 'Application email'), ('missing_document_explanation', 'Missing document explanation'), ('visa_explanation_letter', 'Visa explanation letter'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('exported', 'Exported'), ('saved_to_pack', 'Saved to pack'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('target_organization', models.CharField(blank=True, max_length=255)),
                ('template_key', models.CharField(blank=True, max_length=40)),
                ('content_style', models.CharField(blank=True, max_length=40)),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('plain_text_preview', models.TextField(blank=True)),
                ('ats_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('ai_model', models.CharField(blank=True, max_length=128)),
                ('credits_charged', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.trackedapplication')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_application_documents', to='documents.documentbundle')),
                ('created_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_application_documents', to='documents.document')),
                ('exported_docx_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_docx_for', to='documents.documentfile')),
                ('exported_pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdf_for', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_application_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='documents_g_owner_i_c7ac00_idx'), models.Index(fields=['owner', 'bundle'], name='documents_g_owner_i_8ed43f_idx'), models.Index(fields=['owner', 'application'], name='documents_g_owner_i_57a98b_idx')],
            },
        ),
    ]
