# Generated by Django 5.2.15 on 2026-06-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_generatedapplicationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('file', 'Uploaded file'), ('text', 'Pasted text/email'), ('link', 'Pasted link')], max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzed', 'Analyzed'), ('applied', 'Applied'), ('archived', 'Archived'), ('failed', 'Failed')], default='new', max_length=12)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('pasted_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('credits_charged', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_inbox_items', to='documents.trackedapplication')),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_inbox_items', to='documents.documentbundle')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_inbox_items', to='documents.document')),
                ('linked_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_inbox_items', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_inbox_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-updated_at'], name='documents_m_owner_i_253db6_idx'), models.Index(fields=['owner', 'item_type'], name='documents_m_owner_i_029c59_idx')],
            },
        ),
    ]
