# Generated by Django 5.2.15 on 2026-06-24 12:36

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_magicinboxitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('opened', 'Opened'), ('uploaded', 'Uploaded'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_replacement', 'Needs replacement'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_document_title', models.CharField(max_length=255)),
                ('requested_document_type', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_message', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uploads', models.PositiveSmallIntegerField(default=1)),
                ('upload_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('owner_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_request_links', to='documents.document')),
                ('linked_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_request_links', to='documents.trackedapplication')),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_request_links', to='documents.documentbundle')),
                ('linked_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_request_links', to='documents.documentbundlerequirement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_request_links', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_request_links', to='documents.documentfile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-updated_at'], name='documents_d_owner_i_88f2f5_idx'), models.Index(fields=['owner', 'due_date'], name='documents_d_owner_i_58f7dd_idx')],
            },
        ),
    ]
