# Generated by Django 5.2.15 on 2026-06-24 13:14

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_documentrequestlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(choices=[('application', 'Application'), ('pack', 'Pack'), ('emergency', 'Emergency'), ('client', 'Client'), ('employee', 'Employee'), ('general', 'General')], default='general', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('archived', 'Archived')], default='active', max_length=12)),
                ('token', models.CharField(db_index=True, default=apps.documents.models.generate_share_token, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_upload', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharing_rooms', to='documents.trackedapplication')),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharing_rooms', to='documents.documentbundle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SharingRoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('document', 'Document'), ('file', 'File'), ('request', 'Document request')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_room_items', to='documents.document')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_room_items', to='documents.documentfile')),
                ('request_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_room_items', to='documents.documentrequestlink')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.sharingroom')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SharingRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permission', models.CharField(choices=[('view', 'View'), ('upload', 'Upload'), ('view_upload', 'View and upload')], default='view', max_length=12)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='documents.sharingroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharingroom',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='documents_s_owner_i_b10ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharingroom',
            index=models.Index(fields=['owner', 'room_type'], name='documents_s_owner_i_5b39d3_idx'),
        ),
        migrations.AddIndex(
            model_name='sharingroomitem',
            index=models.Index(fields=['room', 'item_type'], name='documents_s_room_id_8e43db_idx'),
        ),
    ]
