# Generated by Django 5.2.15 on 2026-06-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_sharingroom_sharingroomitem_sharingroomparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedDocumentCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('protection_type', models.CharField(choices=[('watermark', 'Watermark'), ('redaction', 'Redaction'), ('redaction_watermark', 'Redaction + watermark')], default='redaction_watermark', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('watermark_text', models.CharField(blank=True, max_length=120)),
                ('watermark_position', models.CharField(choices=[('diagonal', 'Diagonal'), ('center', 'Center'), ('footer', 'Footer'), ('header', 'Header')], default='diagonal', max_length=10)),
                ('watermark_opacity', models.FloatField(default=0.25)),
                ('redactions', models.JSONField(blank=True, default=list)),
                ('output_mime_type', models.CharField(blank=True, max_length=120)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('original_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_copies_from', to='documents.document')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_copies_from', to='documents.documentfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_document_copies', to=settings.AUTH_USER_MODEL)),
                ('protected_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_copy_output', to='documents.document')),
                ('protected_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_copy_output', to='documents.documentfile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-created_at'], name='documents_p_owner_i_ca7b27_idx'), models.Index(fields=['owner', 'original_file'], name='documents_p_owner_i_7b0945_idx')],
            },
        ),
    ]
