# Generated by Django 5.2.15 on 2026-06-24 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_protecteddocumentcopy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('owner', 'Owner'), ('authenticated_user', 'Authenticated user'), ('public_link', 'Public link visitor'), ('system', 'System')], default='owner', max_length=20)),
                ('actor_label', models.CharField(blank=True, max_length=80)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('document', 'Document'), ('file', 'File'), ('document_request', 'Document request'), ('sharing_room', 'Sharing room'), ('protected_copy', 'Protected copy'), ('application', 'Application'), ('pack', 'Pack'), ('security', 'Security'), ('system', 'System')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=60)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('related_object_label', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='documents_a_owner_i_fe2525_idx'), models.Index(fields=['owner', 'category', '-created_at'], name='documents_a_owner_i_ac271f_idx'), models.Index(fields=['owner', 'event_type', '-created_at'], name='documents_a_owner_i_13946a_idx'), models.Index(fields=['owner', 'object_type', 'object_id'], name='documents_a_owner_i_daed6f_idx')],
            },
        ),
    ]
