# Generated by Django 5.2.15 on 2026-06-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auditlogentry'),
        ('organizations', '0009_alter_portalcase_case_type_organizationcasetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('collection_type', models.CharField(choices=[('manual', 'Manual'), ('saved_view', 'Saved view'), ('system', 'System')], default='manual', max_length=12)),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.SlugField(blank=True, max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('folder_type', models.CharField(choices=[('normal', 'Normal'), ('system', 'System'), ('case', 'Case'), ('person', 'Person'), ('template', 'Template')], default='normal', max_length=12)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocumentStructurePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_mode', models.CharField(choices=[('by_person', 'By person'), ('by_case', 'By case'), ('by_document_type', 'By document type'), ('by_template', 'By template'), ('custom', 'Custom')], default='by_person', max_length=20)),
                ('auto_create_case_folder', models.BooleanField(default=True)),
                ('auto_create_person_folder', models.BooleanField(default=True)),
                ('auto_file_accepted_uploads', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTemplateFolderBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documenttag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['organization', 'slug'], name='documents_d_organiz_56dd32_idx'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_collections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_collections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcollectionitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_collection_items_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentcollection'),
        ),
        migrations.AddField(
            model_name='documentcollectionitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='documents', through='documents.DocumentCollectionItem', to='documents.documentcollection'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='linked_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders', to='organizations.portalcase'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='linked_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders', to='organizations.portalperson'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='linked_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders', to='organizations.organizationcasetemplate'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder'),
        ),
        migrations.AddField(
            model_name='document',
            name='primary_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder'),
        ),
        migrations.AddField(
            model_name='organizationdocumentstructurepreference',
            name='default_root_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_default_for', to='documents.documentfolder'),
        ),
        migrations.AddField(
            model_name='organizationdocumentstructurepreference',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_structure_preference', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationdocumentstructurepreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_structure_prefs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationtemplatefolderblueprint',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_blueprints', to='organizations.organizationcasetemplate'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['owner', 'collection_type'], name='documents_d_owner_i_7c7c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['organization', 'collection_type'], name='documents_d_organiz_e84a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollectionitem',
            index=models.Index(fields=['collection', 'created_at'], name='documents_d_collect_614635_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentcollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'document'), name='unique_document_per_collection'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['owner', 'is_archived', 'sort_order'], name='documents_d_owner_i_0026ed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'is_archived', 'sort_order'], name='documents_d_organiz_7f2f64_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['parent'], name='documents_d_parent__408df5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtemplatefolderblueprint',
            index=models.Index(fields=['template', 'sort_order'], name='documents_o_templat_a8faec_idx'),
        ),
    ]
