# Generated by Django 5.2.15 on 2026-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_documentcollection_documentcollectionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfileactivity',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentfileactivity',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roomactivity',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roomactivity',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
