# Generated by Django 5.2.15 on 2026-06-16 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_request_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequestsubmission',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='documentrequestsubmission',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationdocumentfile',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='organizationdocumentfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
