# Generated by Django 5.2.15 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_documentrequestsubmission_file_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
