# Generated by Django 5.2.15 on 2026-06-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auditlogentry'),
        ('organizations', '0004_organization_brand_color_organization_logo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('person_type', models.CharField(choices=[('client', 'Client'), ('student', 'Student'), ('applicant', 'Applicant'), ('employee', 'Employee'), ('family_member', 'Family member'), ('other', 'Other')], default='client', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting_for_documents', 'Waiting for documents'), ('under_review', 'Under review'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_people_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_people', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('visa', 'Visa'), ('scholarship', 'Scholarship'), ('admission', 'Admission'), ('employee_onboarding', 'Employee onboarding'), ('compliance', 'Compliance'), ('client_file', 'Client file'), ('general', 'General')], default='general', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting_documents', 'Collecting documents'), ('waiting_for_review', 'Waiting for review'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cases_created', to=settings.AUTH_USER_MODEL)),
                ('linked_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cases', to='documents.trackedapplication')),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cases', to='documents.documentbundle')),
                ('linked_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cases', to='documents.sharingroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_cases', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='organizations.portalperson')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalCaseDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_requests', to='organizations.portalcase')),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_case_links', to='documents.documentrequestlink')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_case_requests', to='documents.documentbundlerequirement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='organizatio_case_id_4ad874_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='portalperson',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='organizatio_organiz_3b7fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='portalcase',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='organizatio_organiz_41184c_idx'),
        ),
        migrations.AddIndex(
            model_name='portalcase',
            index=models.Index(fields=['organization', 'person'], name='organizatio_organiz_5d3775_idx'),
        ),
    ]
