# Generated by Django 5.2.15 on 2026-06-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_portalperson_portalcase_portalcasedocumentrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPlanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('teams_beta', 'Teams (beta)'), ('teams', 'Teams'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('disabled', 'Disabled'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('portal_enabled', models.BooleanField(default=False)),
                ('max_members', models.PositiveIntegerField(blank=True, null=True)),
                ('max_portal_people', models.PositiveIntegerField(blank=True, null=True)),
                ('max_active_portal_cases', models.PositiveIntegerField(blank=True, null=True)),
                ('max_active_document_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('max_active_sharing_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_profile', to='organizations.organization')),
            ],
        ),
    ]
