# Generated by Django 5.2.15 on 2026-06-25 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auditlogentry'),
        ('organizations', '0006_organizationplanprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCaseReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_replacement', 'Needs replacement')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notified_recipient', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='decision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='last_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='review_status',
            field=models.CharField(choices=[('pending_upload', 'Pending upload'), ('uploaded', 'Uploaded'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_replacement', 'Needs replacement'), ('cancelled', 'Cancelled')], default='pending_upload', max_length=20),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_reviews_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalcasedocumentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='portalcasedocumentrequest',
            index=models.Index(fields=['review_status'], name='organizatio_review__a964a0_idx'),
        ),
        migrations.AddField(
            model_name='portalcasereviewdecision',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='organizations.portalcase'),
        ),
        migrations.AddField(
            model_name='portalcasereviewdecision',
            name='case_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='organizations.portalcasedocumentrequest'),
        ),
        migrations.AddField(
            model_name='portalcasereviewdecision',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalcasereviewdecision',
            name='document_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_review_decisions', to='documents.documentrequestlink'),
        ),
        migrations.AddField(
            model_name='portalcasereviewdecision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_review_decisions', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='portalcasereviewdecision',
            index=models.Index(fields=['case_request', '-decided_at'], name='organizatio_case_re_1c973d_idx'),
        ),
    ]
