# Generated by Django 5.2.15 on 2026-06-25 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auditlogentry'),
        ('organizations', '0007_portalcasereviewdecision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalReminderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('missing_documents', 'Missing documents'), ('overdue_requests', 'Overdue requests'), ('needs_replacement', 'Needs replacement'), ('rejected_documents', 'Rejected documents'), ('due_soon_cases', 'Due soon cases'), ('collecting_documents', 'Collecting documents')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partially_failed', 'Partially failed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_intro', models.TextField(blank=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_batches', to='organizations.portalcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_reminder_batches_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_reminder_batches', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalReminderRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('skip_reason', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='organizations.portalreminderbatch')),
                ('case_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_recipients', to='organizations.portalcasedocumentrequest')),
                ('document_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_reminder_recipients', to='documents.documentrequestlink')),
                ('portal_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_recipients', to='organizations.portalcase')),
                ('portal_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_recipients', to='organizations.portalperson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalreminderbatch',
            index=models.Index(fields=['organization', '-created_at'], name='organizatio_organiz_4b5cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreminderbatch',
            index=models.Index(fields=['organization', 'reminder_type', '-created_at'], name='organizatio_organiz_26b52c_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreminderrecipient',
            index=models.Index(fields=['batch', 'status'], name='organizatio_batch_i_5fa072_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreminderrecipient',
            index=models.Index(fields=['recipient_email', 'status', '-created_at'], name='organizatio_recipie_70d918_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreminderrecipient',
            index=models.Index(fields=['case_request', '-created_at'], name='organizatio_case_re_669349_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreminderrecipient',
            index=models.Index(fields=['portal_case', '-created_at'], name='organizatio_portal__f5c49f_idx'),
        ),
    ]
