# Generated by Django 5.2.15 on 2026-06-25 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_portalreminderbatch_portalreminderrecipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcase',
            name='case_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('scholarship', 'Scholarship'), ('admission', 'Admission'), ('employee_onboarding', 'Employee onboarding'), ('compliance', 'Compliance'), ('client_file', 'Client file'), ('insurance_claim', 'Insurance claim'), ('grant', 'Grant'), ('internship', 'Internship'), ('general', 'General')], default='general', max_length=24),
        ),
        migrations.CreateModel(
            name='OrganizationCaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('case_type', models.CharField(default='general', max_length=24)),
                ('default_case_title', models.CharField(blank=True, max_length=255)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('default_due_days', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_create_pack', models.BooleanField(default=True)),
                ('auto_create_room', models.BooleanField(default=True)),
                ('auto_create_requests', models.BooleanField(default=False)),
                ('default_room_title', models.CharField(blank=True, max_length=255)),
                ('default_room_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_templates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCaseTemplateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('request_message', models.TextField(blank=True)),
                ('due_days_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_file_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='organizations.organizationcasetemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationcasetemplate',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='organizatio_organiz_a76dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcasetemplaterequirement',
            index=models.Index(fields=['template', 'sort_order'], name='organizatio_templat_051dd3_idx'),
        ),
    ]
