# Generated by Django 5.2.15 on 2026-06-25 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_portalcase_case_type_organizationcasetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcasetemplate',
            name='default_custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationcasetemplate',
            name='default_custom_status_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='OrganizationCaseStatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('planning', 'Planning'), ('collecting', 'Collecting'), ('reviewing', 'Reviewing'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('closed', 'Closed')], max_length=12)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('maps_to_system_status', models.CharField(blank=True, choices=[('planning', 'Planning'), ('checklist_created', 'Checklist created'), ('documents_missing', 'Documents missing'), ('ready_to_submit', 'Ready to submit'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('renewal_needed', 'Renewal needed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_status_definitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='portalcase',
            name='custom_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='organizations.organizationcasestatusdefinition'),
        ),
        migrations.CreateModel(
            name='OrganizationCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('target', models.CharField(choices=[('person', 'Person'), ('case', 'Case')], max_length=8)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('single_select', 'Single select'), ('multi_select', 'Multi select'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public_readonly', 'Public read-only'), ('public_editable', 'Public editable')], default='internal', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_fields_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organizations.organization')),
            ],
            options={
                'ordering': ['target', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='organizations.portalcase')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='organizations.organizationcustomfield')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='organizations.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='organizations.portalperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='organizationcasestatusdefinition',
            index=models.Index(fields=['organization', 'is_active', 'sort_order'], name='organizatio_organiz_25d323_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcasestatusdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_case_status_key_per_org'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomfield',
            index=models.Index(fields=['organization', 'target', 'is_active', 'sort_order'], name='organizatio_organiz_832ea5_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomfield',
            constraint=models.UniqueConstraint(fields=('organization', 'target', 'key'), name='unique_custom_field_key_per_org_target'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomfieldvalue',
            index=models.Index(fields=['organization', 'field'], name='organizatio_organiz_8217b3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomfieldvalue',
            index=models.Index(fields=['person'], name='organizatio_person__262015_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomfieldvalue',
            index=models.Index(fields=['case'], name='organizatio_case_id_bc6b4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('field', 'person'), name='unique_field_value_per_person'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('field', 'case'), name='unique_field_value_per_case'),
        ),
    ]
